gadget-inc/js-clients

- packages/react/package.json
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGet.ts
The new version of `api-client-core` includes improvements to the `Select` type, which makes the result types for all of our hooks be properly typed when selecting an array/nullable type. This unfortunate led to TS complaining about:
> Type instantiation is excessively deep and possibly infinite
on the return types. Adding an additional generic parameter for the schema seems to have resolved this issue. I can't explain why, unfortunately.
One question: should we consider a different version specifier for now, that is a little more loose? I was thinking `~0.3` (>=0.3, <1) instead of `^0.3` (>= 0.3, <0.4).
> Bump api-client-core dep in react to ^0.4

- .github/actions/setup-test-env/action.yml
- .github/workflows/test.yml
- package.json
- packages/react/package.json
- packages/react/spec/apis.ts
- packages/react/spec/useAction.spec.ts
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/useGet.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGet.ts
- yarn.lock
When working on some example apps I went to use a plain ole `useFindMany(api.widget)` without passing a `select` option and found there to be no typed return value! The implementation supports this just fine, but we needed one little extra step to default the `select` option at type time as well as at runtime. This adds that, as well as a bunch of type-time tests that assert it works. To type test in this package I added some example clients that we yarn install from production Gadget apps which feels a little weird but I think buys us a lot of confidence so I think we aught to do it.
> [react] Typed default selection support

- packages/api-client-core/spec/FieldSelection.spec.ts
- packages/api-client-core/src/FieldSelection.ts
- packages/api-client-core/src/operationBuilders.ts
Adding `__typename`  to outgoing graphql queries allows urql's default caching mechanism to refetch operations when it knows something has changed! See https://formidable.com/open-source/urql/docs/basics/document-caching/ for more details. For folks building stuff with `@gadgetinc/react`, this is really useful to just get by default without having to configure anything. We select the `__typename` field along with `id` and whatever else the user has asked for, and then urql does fancy stuff to inspect which typenames have changed when a mutation is run and refetch any queries also touching those typenames. 
Someday we should 100% support the normalized caching thing right out of the box, but I think it is wise to stick with the simple typename based approach that urql itself defaults to …
> Include the __typename field in the default generated selections

- packages/api-client-core/package.json
- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/support.ts
- v0.4.4
- Throw real error objects from inside our success assertion helpers so they have stacks for the user to trace
- Add support for the internal deleteMany mutation to InternalModelManager
> delete many mutation

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetConnection.ts
- yarn.lock
This switches us over to using the built in bits of urql that support file uploads over graphql. We're gonna use https://github.com/jaydenseric/graphql-upload on the backend which `@urql/exchange-multipart-fetch` works with well! This exchange is a drop in replacement for the normal fetch exchange if you're not uploading files also, so we can roll it out ahead of time. 
All the integration testing of this thing is gonna happen Gadget side.
See https://formidable.com/open-source/urql/docs/api/multipart-fetch-exchange/ for more info on it.
> Switch to the multipart fetch exchange for urql to support file uploads

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetConnection.ts
Previously, there was a chance that if the connection was established very quickly, we may have missed the "connected" event from the websocket before we created the listener in `connectionOpen`. This would result in a false timeout from our own `setTimeout`, which always rejects.
To handle this scenario, we ensure a connected listener is given in the construction of the subscription client that tracks the status.
**TODO:**
> Better handle connected states

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetConnection.ts
Set the WS connection timeout - the time we wait for the `onConnect` callback to run at 10s. (2x the previous value).
And allow users of the client to pass a different timeout in to avoid needing to change the client when we update this value in the future.
> Add a configurable ws timeout

- .eslintrc.js
- .github/workflows/test.yml
- .gitignore
- package.json
- packages/react/package.json
- scripts/check-dependency-versions.ts
- scripts/tsconfig.json
- yarn.lock
I added a script so that our binding packages don't accidentally depend on an incompatible version of `@gadgetinc/api-client-core`.
This should help prevent our generated clients from using a `@gadgetinc/api-client-core` version that our bindings don't support - which causes TypeScript to complain.
> Added script to make sure api-client-core dep versions are correct

- .github/workflows/release.yml
- .github/workflows/test.yml
- Contributing.md
Added a `release.yml` workflow to automatically publish our packages. It uses [this action](https://github.com/JS-DevTools/npm-publish) under the hood which only publishes a package if it's `package.json`'s `version` changes.
I made the `release.yml` workflow re-use the `test.yml` workflow so we don't have to duplicate our test steps. The `release.yml` is only set to run on the main branch.
I know I initially wanted to have this be a manual action but I changed my mind... go fast and break things right!?
> Add release workflow to automatically publish npm packages

- tsconfig.json
**What**
This fixes our source map issues when someone uses our react client with create-react-app v5.
```shell
Failed to parse source map from 'node_modules/@gadgetinc/api-client-core/src/AnyClient.ts' file:
Error: ENOENT: no such file or directory, open 'node_modules/@gadgetinc/api-client-core/src/AnyClient.ts'
Failed to parse source map from 'node_modules/@gadgetinc/react/src/index.ts' file:
Error: ENOENT: no such file or directory, open 'node_modules/@gadgetinc/react/src/index.ts'
```
**Why**
Because we want a seamless out-of-the-box experience with creact-react-app.
**How**
Webpack can't find the original source code that our source maps are pointing to, so we have 2 options:
1. Include the `src` directory in our bundle
2. Set `inlineSources: true` in our tsconfig.json
I went with …
> Added inlineSources: true to tsconfig.json

- packages/api-client-core/package.json
- yarn.lock
The source map fix for gql-query-builder [was merged](https://github.com/atulmy/gql-query-builder/pull/69) 🎉
Let's update to the newest version.
> Update gql-query-builder to v3.6.0

- package.json
This will solve the problem I had [releasing v.0.5.2](https://github.com/gadget-inc/js-clients/actions/runs/2036689687).
**Problem**
Our `@gadgetinc/react` tests use `@gadget-client/bulk-actions-example` and `@gadget-client/related-products-example` which are generated clients from gadget. The generated clients depend on `@gadgetinc/api-client-core` and pin their dependency version - in this case they were pinned to v0.5.1.
`@gadgetinc/react` also depends on `@gadgetinc/api-client-core`, but it's only pinned to v0.5, so yarn installed `@gadgetincapi-client-core@0.5.1` for the generated clients but let `@gadgetinc/react` use the new monorepo version v0.5.2.
This caused `@gadgetinc/react` and our generated clients to use different `@gadgetinc/api-core-client` versions which causes …
> Add api-client-core resolution

- packages/api-client-core/package.json
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/support.ts
- packages/react/package.json
- packages/react/src/useFindFirst.ts
Supports [sc-1556]
Adds logic to properly address empty `findFirst` empty results. The base `findMany` runner and internal method now account for 3 possible expected behaviours:
1. For `findMany`, where results of empty array are possible.
2. For `findFirst`, where results of empty array throw an error.
3. For `maybeFindFirst`, where results of an empty array are returned as `null`, with no error thrown.
> Fix empty `findFirst` cases

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/GadgetRecord.ts
- packages/api-client-core/src/GadgetRecordList.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/support.ts
- packages/react/package.json
- packages/react/src/useMaybeFindOne.ts
The `maybeFindOne` func + hook were not properly checking for non-null types — the hydration process was creating an object with a few basic properties.
Added proper checking for this, in that way that doesn't make TS scream.
> Fix type check in `maybeFindOne`

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetRecord.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationRunners.ts
Unfortunately, the signature change to the `findOne` function resulted in typing issues, even with the overload designed to prevent it.
However, I've added a robust way to check if the record is empty, on the GadgetRecord class itself, so I'm no longer relying on the `id` prop.
> Restore original signature of `findOne` function

- packages/api-client-core/package.json
- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
Implements conditional arguments for `search`, `sort` and `filter` for the internal find many query. The internal version of https://github.com/gadget-inc/js-clients/pull/31.
In order to make this easier I have converted this to also use the graphql query builder that is used by the `operationBuilder` to generate the query rather than using a hardcoded string. I have also broken out into 2 methods for the `findFirst` case and the default `findMany` as the queries were sufficiently different (no pagination options, no page info, no cursor and different operation name). This meant I could remove a bunch conditional logic within the query itself. 
I have added a bunch of tests similar to those in `operationBuilder.spec` for the generated queries.
> Use query builder for internal find many query

- packages/api-client-core/package.json
- packages/api-client-core/src/ClientOptions.ts
- packages/api-client-core/src/GadgetConnection.ts
This will allow us to manage browser session tokens our self for the public app oauth flow.
fixes ggt-1457
> Add option to specify initial browser session token

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetConnection.ts
I was wondering why auth wasn't working with the `initialToken` option, and then I realized it was being clobbered by the existing setup that sets it when the websocket connection is opened :woman_facepalming:
> Don't override `initialToken` on ws connect

- packages/react/package.json
I haven't found any incompatibilities with this library and react 18 --
but if you try to install it on a project with react 18 you will get a
peer dependency error, I think we can support both
https://linear.app/gadget-dev/issue/GGT-1522/gadgetincreact-is-not-compatible-with-react-18
> chore(react): expand react peer dependency to include ^18.0.0

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react-shopify-app-bridge/src/utils.ts
We need to be able to support the same host on multiple apps so we'll need to keep tokens by both the shopify api key as well as host.
closes GGT-1734
> Create token key by host and shopify api key

- packages/api-client-core/package.json
- packages/api-client-core/spec/GadgetConnection.spec.ts
- packages/api-client-core/src/ClientOptions.ts
- packages/api-client-core/src/GadgetConnection.ts
- yarn.lock
To build support for Shopify session token authentication, we need the client to be able to set arbitrary headers to send back to the Gadget backend. We don't wanna build super bespoke shopify code into a client used in a variety of non-shopify places, so this adds a hook were folks constructing the connection can create connections that pass a function that does whatever it wants to the outgoing request. Woop woop!
> Add support for a custom auth method which can be used to implement platform native auths from userland

- packages/api-client-core/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
Need to deploy the api-client-core changes so that the shopify react package can use the new custom auth.
> Bump minor version of api-client-core

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
We recently added a `shopifyConnection` GraphQL query that allows the `Provider` to know whether or not we should re-auth with Shopify for updated scopes. This PR requests the `requiresReauthentication` field and forces a re-authentication if that returns true.
closes GGT-1850
> Reauthenticate if scopes have changed

- packages/react-shopify-app-bridge/package.json
- yarn.lock
Shopify released v3 of their app bridge and we should support the new version. I did some basic testing with faker and didn't see any compatibility issues. We should add some tests for this at some point
> Update peer dependencies for react-shopify-app-bridge

- packages/api-client-core/package.json
- packages/api-client-core/tsconfig.json
We ran into some issues with NextJs minification where it cannot correctly minify code that uses null coalescing. Let's compile down to `es2919` instead where null coalesce does not exist. Will bump deps for other packages once this one is merged
before:
after:
> Change api-client-core to target es2019 instead of es2020

- packages/react-shopify-app-bridge/README.md
- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react-shopify-app-bridge/src/context.ts
I'm not entirely sure what to call this flag but it is there to indicate that the page has rendered because a user has visited the page directly via something like a link instead of the shopify admin (if the app is set as embedded). This is so that developers can add their own behavior i.e. redirect to app listing, ask for shop url to install on, or show some splash page.
> Add a flag to let developers know that they're viewing a page request

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/package.json
The Provider makes a query 
```graphql
query GetSessionForShopifyApp {
currentSession {
id
shop {
id
}
}
shopifyConnection {
requiresReauthentication
}
}
```
To determine if the scopes are up to date and the session is valid. 
If the `Shop` record was removed on the Gadget back-end, but the app remained embedded. The app provider would hit a situation where it can't find a Session since we first need the Shop record to validate the Session JWT token. 
We fix this by no longer assuming `currentSession` is present (it wont be if the shop record is missing), and instead just look at the `requiresReauthentication` value on its own.
This goes along with  a change to the GraphQL API here https://github.com/gadget-inc/gadget/pull/4001
> Fix requiresReauthentication check for missing shop records

- packages/api-client-core/package.json
- packages/api-client-core/spec/GadgetConnection.spec.ts
- packages/api-client-core/src/GadgetTransaction.ts
- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/package.json
- packages/react/spec/useAction.spec.ts
- packages/react/spec/useBulkAction.spec.ts
- yarn.lock
https://github.com/FormidableLabs/urql/blob/main/packages/core/CHANGELOG.md
urql has went through a major version bump. Nothing particularly breaking in here, minus the requirement to provide a variables object to some of the methods. The multipart fetch exchange went to 1.0 to support the `@urql/core` bump.
This is a prerequisite to introducing the same bump in the gadget server, which in turn is needed for introducing some other urql packages that are being built around version 3. Tests show this bump doesn't break anything over there.
> Bump urql in all client packages.

- packages/api-client-core/spec/InvalidRecordError.spec.ts
- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/support.ts
The object already captures what was invalid about which fields, but in some contexts Gadget side, we can provide more details about the record which failed validation etc.
Corresponds to gadget-inc/gadget#4006
> Make InvalidRecordErrors capture structured data about the record and model which was invalid

- packages/api-client-core/src/support.ts
- packages/react/spec/ErrorWrapper.spec.ts
- packages/react/spec/useAction.spec.ts
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/useGet.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGet.ts
- packages/react/src/useGlobalAction.ts
- packages/react/src/useMaybeFindFirst.ts
- packages/react/src/useMaybeFindOne.ts
- packages/react/src/utils.ts
- yarn.lock
When a Gadget backend rejects an action because the supplied params are invalid, it returns an error in the format like:
```
{
success: false,
errors: {
message: "GGT_INVALID_RECORD: Record is invalid. 2 error needs to be corrected",
validationErrors: [
{ field: "title", message: "is too short" },
{ field: "body", message: "is required" }
]
}
```
The point of all that is to always return a top level error message regardless of what kind of error happened (be it like a backend error where all we have is a message) and then provide structured error details if we do have them (the by-field error messages).
This data is really useful for driving form validations where you want to show a user which fields are broken. They need to correct those fields before they can move on, so we need to make …
> [hooks] Return a Gadget-owned error wrapper object with easy access to validation errors from GraphQL responses

- Readme.md
- packages/api-client-core/src/GadgetRecordList.ts
- packages/react/README.md
- packages/react/src/useAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGet.ts
Adds api docs and some short examples for using the react hooks. Next step: embedding this same content into the Gadget docs at docs.gadget.dev . I find reviewing markdown kind of unpleasant, so here's a link to the rendered version: https://github.com/gadget-inc/js-clients/blob/docs/packages/react/README.md
> React docs

- packages/react/README.md
- packages/react/package.json
- packages/react/src/index.ts
We currently export the urql Provider from our react package so let's do the same for `useQuery` and `useMutation`. This allows users to use the same version urql that our react package uses and not rely on a peer dependency should they need custom queries or mutations. We use the provider and `useQuery` in `@gadgetinc/react-shopify-app-bridge`
> Export useQuery and useMutation from react package

- packages/api-client-core/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
Bump the peer dependency versions for `@gadgetinc/react` in `@gadgetinc/react-shopify-app-bridge`. Also update to use `useQuery` from `@gadgetinc/react` instead of `urql`. Won't bump the version for now and can wait for the version bump when we merge [PR#45](https://github.com/gadget-inc/js-clients/pull/45)
> React shopify deps

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
We're updating Gadget's Shopify OAuth URLs to be app specific e.g. https://sample.gadget.app/api/connections/auth/shopify vs https://app.gadget.dev/connections/auth/shopify/callback. This PR updates `react-shopify-app-bridge` to use the new app specific route instead of the root domain.
This shouldn't be merged before https://github.com/gadget-inc/gadget/pull/3558
closes GGT-1744.
> Updating react-shopify-app-bridge oauth url to be app specific

- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- yarn.lock
I want to start using `@testing-library/react` to test our react hooks, but it's `renderHook` test function only exists in a newer version that only supports React 18. I figure that our users are likely to use React 18 if they are just using `create-react-app` or `next.js`, so we should probably be testing against it anyways.
> Bump development version of react we test against to react 18

- packages/api-client-core/jest.config.js
- packages/react-shopify-app-bridge/jest.config.js
- packages/react/jest.config.js
Jest 29 changed the inclusion by default -- this restricts us to only run tests in our root spec folder instead of in the dist folder.
> Don't run specs in the built dist folders

- packages/api-client-core/package.json
- packages/api-client-core/spec/GadgetRecord.spec.ts
- packages/api-client-core/src/GadgetRecord.ts
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- Improved GadgetRecord performance, by greatly minimizing the number of object-to-array conversions, and avoiding generating all changes just to see if there is one change.
- Added `currentChanges` method to get the current value of changed fields, rather than both current AND previous values in a nested object.
- Added a new test for this feature.
> Add a `currentChanges` to `GadgetRecord`

- packages/react/spec/testWrapper.tsx
- packages/react/spec/useAction.spec.ts
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useGlobalAction.ts
- packages/react/src/utils.ts
We wrap urql's `useMutation` hook to return a fancy hydrated value with our own error class and our own hydrated data. This worked for the `const [result] = useAction` bit, but wasn't applied to the `const [_, run] = useAction(); const result = await run()` part.
This fixes that woop woop!
> Wrap `useAction` promise results

- packages/react-shopify-app-bridge/README.md
- packages/react-shopify-app-bridge/src/Provider.tsx
Closes #103
It was brought that Shopify's app bridge react provider accepts a custom router config if you wanted to do your own client side routing. Let's allow the same interface to be specified for our own wrapper and pass that to the app bridge provider.
> Pass through custom router config to shopify app bridge

- packages/react/spec/testWrapper.tsx
- packages/react/spec/useGadgetMutation.spec.ts
- packages/react/spec/useGadgetQuery.spec.ts
- packages/react/src/GadgetProvider.tsx
- packages/react/src/index.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGadgetMutation.ts
- packages/react/src/useGadgetQuery.ts
- packages/react/src/useGet.ts
- packages/react/src/useGlobalAction.ts
- packages/react/src/useMaybeFindFirst.ts
- packages/react/src/useMaybeFindOne.ts
- packages/react/src/useStructuralMemo.ts
- packages/react/src/utils.ts
Problems:
- No proper error if the user doesn't include the provider.
- urql will create a client that points to `/graphql` if the provider is not included.
- urql has no parameter to get the url of the client.
Solution:
- Create a provider that wrap the urql provider, then check to see if that provider's context has a client in it.
> GGT-2034 - New provider for react library

- packages/react/package.json
We didn't update `@gadgetinc/react` package version after merging #112
> bump @gadgetinc/react version

- packages/react-shopify-app-bridge/package.json
We need to update the dependent version of `@gadgetinc/react` in the `@gadgetinc/react-shopify-app-bridge` package
> Updating react shopify app bridge dependency

- packages/api-client-core/src/GadgetRecordList.ts
- packages/react/README.md
- packages/react/spec/testWrapper.tsx
- packages/react/spec/useFindMany.spec.ts
- packages/react/src/useFindMany.ts
It's important that react hook users are able to inquire about the pageInfo returned by a connection, so they can paginate forwards or backwards and know if those pages exist! We tried to make this possible previously but failed by accident -- we were still returning a plain old array of records instead of the extended-array GadgetRecordList object. This updates us to definitely return that fancier object to match the docs that already describe using it, and adds a test that actually exercises those bits to prove it is working.
> hotfix: Return a GadgetRecordList from the useFindMany hook

- packages/api-client-core/spec/GadgetConnection.spec.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/react/README.md
We enable urql's handy dandy client side caching features because they work great and allow for snappy rerenders of components where data hasn't changed. We left it to `urql` to chose the default `requestPolicy`, and their default is `cache-only`. This request policy means that a `refresh()` call made in the browser won't actually refresh by default, you have to pass `refresh({requestPolicy: "network-only"})` to force a network call to be made. I think this default is pretty confusing for users who didn't turn on caching themselves, but I also think the caching sets up a good user experience, so I think we should turn off the full-client-side caching mode.
I also verified that this request policy doesn't really have any effect on imperatively calls made where you do …
> Default urql's requestPolicy to cache-and-network so that users see changed server side data by default

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/spec/GadgetConnection.browser.spec.ts
- packages/api-client-core/spec/GadgetConnection.node.spec.ts
- packages/api-client-core/spec/helpers.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/support.ts
All our docs tell folks to construct their API client with no explicit `authenticationMode` for simplicity, and so that we can make an educated decision about what authentication mode to use internally based on the environment. In Node, we use anonymous authentication, and in the browser, we try to use a cookie-like authentication that works cross-domain with localStorage. 
`localStorage` however errors in some browsers if you try to touch in when the browser window is incognito, or it just doesn't work in private browsing in safari. Sad. This breaks apps trying to get through Shopify's review process, as Shopify requires that you can log in/out of the app in incognito. We support this just fine, you just have to (before this change) ensure you do `new Client({authenticationMode: { …
> Don't use `localStorage` for auth if it isn't available

- .gitignore
- package.json
- packages/api-client-core/spec/GadgetConnectionBrowser.spec.ts
- packages/api-client-core/src/GadgetConnection.ts
- yarn.lock
We noticed that session tokens are stored at the static `token` key and this ends up being re-used across different Gadget apps if you're building multiple embedded apps
closes GGT-2915
> Update storage token to be keyed by endpoint

- packages/api-client-core/spec/GadgetRecordList.spec.ts
- packages/api-client-core/src/GadgetRecordList.ts
Currently if using `nextPage` or `previousPage` we pass either `last` or `first` depending one which way we're paging. This causes issues if `first` or `last` was originally passed as a parameter to fetch the first result set. E.g. if we passed `first: 10` then when we page backwards we send `first: 10, last: 10`, this repeats once we page forward again since we always boot the record list with parameters it was fetched with.
The above works fine when we page backwards but always returns the same page once we try to page forward again.
Will bump version when this gets merged
> do not set both last and first when paging with nextPage or previousPage

- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
We released `0.13.0` of `api-client-core` and updated it in Gagdet's userland deps. This means new clients are generated with `^0.13.0` dependency and no longer resolves to the same version listed under `react` and `react-shopify-app-bridge` (`^0.12.0`). Since we're `<1.0.0`, semver `^0.12.0` only matches the patch version and not the minor version.
Tested locally by installing the current version of client and `react-shopify-app-bridge` which results in the error. Then building a local version with `0.13.0` as the dependency and the error goes away. I updated minor versions for these since `api-client-core` was updated a minor version as well.
closes GGT-3639
> Minor versions of react and react-shopify-app-bridge packages

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetRecord.ts
- packages/api-client-core/src/GadgetRecordList.ts
- packages/api-client-core/src/InternalModelManager.ts
- yarn.lock
This adds an explicit return type to our `toJSON` methods instead of the inferred `any` type.
> Add return explicit return type to `toJSON`

- packages/react/spec/useAction.spec.ts
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/useGet.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGet.ts
- packages/react/src/useGlobalAction.ts
- packages/react/src/useMaybeFindFirst.ts
- packages/react/src/useMaybeFindOne.ts
- yarn.lock
urql takes great care to ensure that if your component rerenders and calls `useQuery` again, but nothing about the query has changed, you get back the same object. This is so that if you use that object in a dependencies array, it's identity is stable and react won't expire memos or re-run useEffects.
Prior to this change, we didn't keep this same property. If you wrote code like this:
```javascript
const [{ data, fetching, error}] = useFindFirst(api.someModel);
const [something, setSomething] = useState(null)
useEffect(() => {
setSomething(data)
}, [data]);
```
You'd accidentally get an infinite loop because the useEffect would trigger a rerender because it called setstate, which would rerun our react hook, which would return new data, which would be passed to the array of dependencies …
> Ensure the react hooks return objects with the same identity if nothing changes on rerender

- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react-shopify-app-bridge/src/context.ts
Since OAuth and any other requests that set this `loading` value are executed almost instantly, setting the default value to false will make components that rely on this value flashes in the first render.
> Change default provider's loading value to true

- packages/react-shopify-app-bridge/package.json
Releasing a new version of the react GadgetProvider which is initially set loading = true
> Release v12.1 with fix to GadgetProvider loading default value

- packages/react-shopify-app-bridge/spec/useGadget.spec.ts
- packages/react-shopify-app-bridge/src/Provider.tsx
When we switched over to using Shopify Session Tokens we broke support for standalone apps that still need to go through OAuth and render some sort of UI. This PR handles the following:
- skip using app bridge altogether if running in standalone mode
- skip requesting a session's shop since that relies on Shopify Session Tokens
- redirect to OAuth endpoint if we're in standalone mode and there is an hmac and shop param
I 🎩  the following flows:
- install a standalone app
- load a standalone app
- install an embedded app
- load an already installed embedded app
- load an embedded app in a non embedded context
> Fix support for standalone mode

- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/support.ts
- packages/react/spec/useFindOne.spec.ts
Changing the error definitions and added missing attributes for errors coming out of the client. We're doing this because of the errors already defined e.g. `GadgetInternalError` weren't being used in appropriate spots.
> change(api-client-core): Error definitions

- packages/api-client-core/package.json
This release is for the changes made here: https://github.com/gadget-inc/js-clients/commit/3144ce116eda1a5d6676a599fbc6605c907c48a6
> bump(api-client-core): v0.13.7

- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
I had a pr [here](https://github.com/gadget-inc/js-clients/pull/189) that passed all tests including lint, and the pr was merged. But no release was generated because the lint test apparently [failed](https://github.com/gadget-inc/js-clients/actions/runs/4919851054). Strange 😞 
Running yarn lint fix in a new branch showed some changes, hopefully this is the real prettier version.
> Linting fix for InternalModelManager

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/src/GadgetConnection.ts
Fixes a bug where `useFetch("/some/path?foo=bar")` would send the included query params URL encoded.
> Ensure that `api.fetch` doesn't mangle query params when used with relative urls

- packages/react/README.md
- packages/react/spec/useFetch.spec.ts
- packages/react/src/useFetch.ts
While working on a form that submitted data to a GET endpoint I found it annoying that `useFetch` insisted on issuing the request as soon as the component renders. I think that is the right default behaviour (kinda like how `useFindMany` starts finding right away), but should be opt-out-able. This adds a new `sendImmediately: false` option to the `useFetch` hook allowing disabling this automatic-send behavior for GET requests.
> useFetch `sendImmediately` option

- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
This PR makes it optional to wrap your model params for create/update in the model api identifier. The only exception is if there is a field with the same api identifier as the model, then the params must be wrapped in the model api identifier; this is because there's no way to tell if the consumer is passing in model params or field value.
It would be nice to be able to test that the correct query/variables are called but the mutations rely on transactions via ws. This is a bit difficult to mock I think without adding some interfaces so that we can create a mock transaction, not sure if that was worth adding here.
> Make passing in the params by model api identifier optional

- packages/api-client-core/package.json
- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/support.ts
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
(ex. hello_world => HelloWorld)
Came back to this ancient bug where model api identifiers with underscores fail to run CRUD API. 
This was because the behavior of the capitalize function was inconsistent with how we name our GraphQL types. 
internally this solves GGT-2123
> fix(api-client-core) - GGT-2123 - Model api identifiers with underscores fail to run CRUD API

- package.json
- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/README.md
- packages/react/spec/testWrapper.tsx
- packages/react/spec/useAction.spec.tsx
- packages/react/src/useAction.ts
- yarn.lock
We need to update the react hooks to also allow optional model api identifiers. This follows the same logic that the internal and public model managers.
closes GGT-4093
> support optional model api identifier in react hooks

- packages/react/package.json
Bumping version to release optional model api identifier in react hooks. Just going to a patch version here since old style calls to `useAction` will continue to work.
> Bump @gadgetinc/react to v0.12.4

- .github/actions/setup-test-env/action.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
The release workflow for this repo broke with the switch to `pnpm`. `pnpm` only comes from the nix env, and not from the github action runner's built in environment, which means the nix env had to be in the shell's environment for it to be available. To do that we can run a login shell by setting the `shell: ` param of each action step. Login shells will source .bash_profile etc where we can hook in to load up the nix environment, but, we can't set the shell for other people's actions.
> Export the nix env to all subshells

- packages/api-client-core/src/AnyClient.ts
- packages/react/README.md
- packages/react/spec/GadgetProvider.spec.tsx
- packages/react/spec/testWrapper.tsx
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useFetch.spec.ts
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/useGet.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/GadgetProvider.tsx
- packages/react/src/index.ts
- packages/react/src/useAction.ts
- packages/react/src/useGadgetMutation.ts
- packages/react/src/useGadgetQuery.ts
This changes the signature of the React `<Provider/>` component in a backwards compatible way to accept the `api` client instance instead of an urql client instance. We're likely to need access to more than just the urql client in the react hooks over time. We already have a nasty hack to get back from the urql client to the actual GadgetConnection object in order to power `useFetch`, and I expect more of this kind of thing to happen in the future. Let's update the API from being
```typescript
<Provider value={api.connection.currentClient} />
```
to be
```typescript
<Provider api={api} />
```
This matches the Shopify provider component, which takes an `api` prop as well.
We ensure this change is backwards compatible by still supporting the `value` prop, and still expecting it to be passed …
> Update the react provider to accept a full instance of an api client instead of just the urql client

- packages/api-client-core/package.json
- pnpm-lock.yaml
Pins `graphql` to `~16.6.0`.
And upgrades the version to `0.13.13`
> Upgrade api-client-core and pin graphql

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/urlParamExchange.ts
We have this Gadget side, I think it'd be really helpful API client side to see in the network tab which operation is doing what:
> Add the graphql operation to the client URL

- packages/react/spec/GadgetProvider.spec.tsx
- packages/react/src/GadgetProvider.tsx
We need this for the auth helpers that ideally don't need to be passed an instance of the api every time, like:
```typescript
export const useSession = () => {
const api = useApi();
const [{ data, fetching, error }] = useGet(api.currentSession, {
select: {
id: true,
state: true,
createdAt: true,
userId: true
}
});
return data;
}
```
With this hook, we can export that kind of framework code, and rely on the user `<Provider/>`-ing us the api client we need
> Add a useApi hook for accessing the current api client without having a reference to it

- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/spec/helpers.ts
- packages/api-client-core/src/InternalModelManager.ts
We recently added a feature to the internal API for only selecting some fields of the returned records. This gives improved performance as the default can exclude computed fields which are often expensive and unused. This feature already exists in the GraphQL API, but the JS client didn't know about it. This teaches it!
I also took the opportunity to type the options and improve the JSDoc comments for the
InternalModelManager class so folks know what the heck this thing does.
This PR Gadget side actually tests this end to end: https://github.com/gadget-inc/gadget/pull/7140
> Add the select option to the internal model manager

- package.json
- packages/api-client-core/package.json
- packages/blog-example/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- pnpm-lock.yaml
- tsconfig.json
Jest tests require the build artifacts from the other workspace packages, which can take a while. For builds to go a bit faster, we can use typescript's handy incremental build support, which allows it to pick up where it left off.
A cold build for me locally:
```
❯ p build
> @gadgetinc/js-clients@0.1.0 build /Users/airhorns/Code/js-clients
> pnpm -r --no-bail run --if-present build
Scope: 4 of 5 workspace projects
packages/api-client-core build$ tsc
└─ Done in 4.9s
packages/react build$ tsc
└─ Done in 6s
packages/react-shopify-app-bridge build$ tsc
└─ Done in 4.3s
```
And then the one after:
```
❯ p build
> @gadgetinc/js-clients@0.1.0 build /Users/airhorns/Code/js-clients
> pnpm -r --no-bail run --if-present build
Scope: 4 of 5 workspace projects
packages/api-client-core build$ tsc
└─ …
```
> Use typescript incremental building for a little bit more speed

- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/support.ts
- packages/blog-example/src/App.tsx
- packages/react/README.md
- packages/react/spec/testWrapper.tsx
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/useGet.spec.ts
- packages/react/src/OptionsType.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGet.ts
- packages/react/src/useMaybeFindFirst.ts
- packages/react/src/useMaybeFindOne.ts
- packages/react/src/utils.ts
React's new Suspense support is the perfect thing for components declaring that they need something to happen before they can fully render. With all the upcoming auth work that we are doing, I think we're going to have lots of situations on the frontend where we want to know current login state, but where we don't have it yet because its a GraphQL call away.
We could solve this by wrapping the whole app in a thing that doesn't render until the session has been fetched. Thats what the `<ClerkProvider/>` does. I think we could do the same thing in our provider, but that'd require us assuming that every provider wants a session, which I don't think is a great assumption.
Instead, I'd rather have the components that need to know login state block, but the ones that don't ... not! We can do …
> Suspense support for React hooks

- packages/api-client-core/spec/GadgetRecord.spec.ts
- packages/api-client-core/src/GadgetRecord.ts
Riley noticed a discord user trying to pass `record.toJSON()` back as an input to a different action call. This didn't work out of the box because the `.toJSON()` includes all the fields that came back from loading the record, including `__typename`. When sending this back at the GraphQL API, the `__typename` attribute causes GraphQL to get mad as you are passing fields which don't exist as input fields.
> Exclude the `__typename` field from GadgetRecord.toJSON()

- packages/api-client-core/src/GadgetConnection.ts
- packages/react/spec/useGadgetMutation.spec.ts
- packages/react/spec/useGadgetQuery.spec.ts
- packages/react/src/GadgetProvider.tsx
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useGadgetQuery.ts
- packages/react/src/useGet.ts
- packages/react/src/useMaybeFindFirst.ts
- packages/react/src/useMaybeFindOne.ts
- packages/react/src/utils.ts
In https://github.com/gadget-inc/js-clients/pull/215, we introduced automatic suspense support for the React query hooks, which allows developers (and us) to mark specific queries with "we want them to suspend" so that urql can do its thing under the hood and do so. We wanted this for a nice api in the `useSession` etc hooks.
To implement this though, we need to turn urql's suspense support on at the client level. This is a constructor option which makes suspense available at all *and* makes it the default for all queries. So that this wasn't a breaking change for all users, I turned on suspense support in the client, but then made all queries pass an explicit `suspense: false` down to urql so the behaviour was unchanged between versions. If a query wants to suspend, it has to opt-in by …
> Set up suspense only in react land

- packages/react/spec/components/auth/SignedIn.spec.tsx
- packages/react/spec/components/auth/SignedInOrRedirect.spec.tsx
- packages/react/spec/components/auth/SignedOut.spec.tsx
- packages/react/spec/utils.ts
- packages/react/src/GadgetProvider.tsx
- packages/react/src/components/auth/SignedIn.tsx
- packages/react/src/components/auth/SignedInOrRedirect.tsx
- packages/react/src/components/auth/SignedOut.tsx
This PR updates the logic to check for user on the session that is signed in/out. Handles a possible scenario in which a user record is deleted without having signed out, and so the session record still exists as `signed-in` with a user id that doesn't actually point anywhere anymore. Our current auth `SignedIn/Out/orRedirect` components would then misbehave and users would get caught in a weird state.
[GGT-4440](https://linear.app/gadget-dev/issue/GGT-4440/signedin-component-renders-children-when-a-session-has-no-user)
Current behaviour 
- with old template: https://hello-test--development.gadget.app/ 
- with new/upcoming template: https://new-auth-template--development.gadget.app/
1. Log in to app
2. Delete user record
3. Refresh app page - weird state, you can go back to `/` / and says …
> Verify Session has associated User for auth components

- packages/react/package.json
- packages/react/spec/components/auth/SignedInOrRedirect.spec.tsx
- packages/react/src/components/auth/SignedInOrRedirect.tsx
This will allow routes to consume the originally intended `pathname` and redirect their once signed in
> Set redirectTo param when redirecting with <SignInOrRedirect />

- packages/react/README.md
- packages/react/package.json
- packages/react/spec/components/auth/SignedOutOrRedirect.spec.tsx
- packages/react/src/components/auth/SignedOutOrRedirect.tsx
We have a `SignedInOrRedirect` component that checks if the user is signed in and if they're not redirect them to the path specified in the `<Provider auth={{signInPath="/"}}>`
We should have a `SignedOutOrRedirect` component that does the opposite so we don't have to do something like 
`<Route index element={isSignedIn ? <Navigate to="/signed-in" /> : <Index />} />`
> Add SignedOutOrRedirect auth component

- packages/react/package.json
- packages/react/src/index.ts
I forgot to export the component in the index file 🤦‍♀️
> Bump gadget/react to 0.13.3

- packages/react/package.json
- packages/react/spec/components/auth/SignedOutOrRedirect.spec.tsx
- packages/react/src/components/auth/SignedOutOrRedirect.tsx
> (fix) Set redirectUrl in SignedOutOrRedirect to the signOutPath

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/src/ClientOptions.ts
- packages/api-client-core/src/GadgetConnection.ts
Outside of Gadget's internal infrastructure, the endpoint the API client is configured with is the public HTTP URL for the app + "/api/graphql". This means we can use the endpoint to infer the public HTTP URL for the app, which we use for building a fully qualified URL when someone does `api.fetch("/some/relative/path")` or `useFetch("/some/relative/path")`.
Sadly, this breaks inside Gadget's infrastructure, where we set up api clients with a custom GraphQL endpoint that uses our internal sandbox<->api connection for performance. The endpoint inside the sandbox is `api.gadget-services.net`, which means `api.fetch("/foo"` becomes a request to `https://api.gadget-services.net/foo`, which isn't right at all. It's weird that folks would be doing `api.fetch` within the sandbox to make an API …
> `baseRouteURL` connection option for proper absolute route building

- packages/react-shopify-app-bridge/gitpkg.config.js
- packages/react-shopify-app-bridge/jest.config.js
- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/spec/imports/cjs-import.js
- packages/react-shopify-app-bridge/spec/imports/imports.spec.ts
- packages/react-shopify-app-bridge/spec/imports/named-esm-import.mjs
- packages/react-shopify-app-bridge/spec/imports/package.json
- packages/react-shopify-app-bridge/spec/useGadget.spec.ts
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react-shopify-app-bridge/src/context.ts
- packages/react-shopify-app-bridge/src/index.ts
- packages/react-shopify-app-bridge/tsconfig.base.json
- packages/react-shopify-app-bridge/tsconfig.cjs.json
- packages/react-shopify-app-bridge/tsconfig.esm.json
- packages/test-bundles/bundles/shopify-read.tsx
- pnpm-lock.yaml
This fixes a bug where react-shopify-app-bridge being CJS only breaks vite setups that use the ESM/CJS versions of @gadgetinc/react as well, where vite imported the ESM version of the react context and the CJS version in two different spots, resulting in context identities not matching.
> Convert react-shopify-app-bridge to also be CJS/ESM

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/src/GadgetProvider.tsx
We should use the new `api` prop when passing in the client to the gadget react client so that devs can use `useApi`.
closes GGT-4604
> Use new api prop to pass in api client in react-shopify-app-bridge

- packages/react/spec/useFetch.spec.ts
- packages/react/src/useFetch.ts
In using the `onComplete` callback its annoying to try and access the completed result of the text stream; this PR passes that value to the `onComplete` callback
> pass the value of the stream to the onComplete callback

- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
releases changes from https://github.com/gadget-inc/js-clients/pull/248
> release @gadgetinc/react 0.14.1

- packages/tiny-graphql-query-compiler/package.json
- packages/tiny-graphql-query-compiler/spec/calls.spec.ts
- packages/tiny-graphql-query-compiler/src/index.ts
- pnpm-lock.yaml
In #231, we dropped the `required` key from the inputs to the `Var` doodad for building graphql queries. This makes the code a bit simpler, but, it was a load-bearing key that the metadata from Gadget passed into api-client-core by means of the metadata on the model managers. So, let's keep supporting it to keep compatibility with already generated api clients and not require a cross-package coordination.
> Restore support for explicitly required variables in the tiny operation compiler

- .github/workflows/test.yml
- package.json
- packages/api-client-core/spec/imports/imports.spec.ts
- packages/api-client-core/spec/support.spec.ts
- packages/react-shopify-app-bridge/spec/imports/imports.spec.ts
- packages/react/spec/imports/imports.spec.ts
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/test-bundles/build.ts
- packages/test-bundles/bundles/shopify-read.tsx
- packages/test-bundles/tsconfig.json
- packages/tiny-graphql-query-compiler/src/index.ts
When I switched js-clients to start publishing both CJS and ESM, I had to mess with the tsconfigs and add separate ones for each build mode. This works fine for the `src` directory of each project, but I missed the fact that because those tsconfigs only apply to the src dirs, running a build only typechecks the `src` dirs. Nothing in CI was typechecking the `spec` dirs or the test bundless, whoops!
This adds an explicit new CI step to typecheck all the files in every package that has a `typecheck` script defined, and fixes a few errors that crept in.
> Fix typecheck in all packages after switch to ESM

- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
We need to update the action runner and builders to take `hasReturnType` into consideration when generating graphQL and selecting the result. This also updates the hooks to do the same. To release this we should first release api-client-core, then update gadget, and then react
> Support custom return types from actions

- packages/react/spec/useAction.spec.tsx
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useGlobalAction.ts
- packages/react/src/utils.ts
Antoine and I both created param-less actions recently, and went to run them using `mutate()` as returned by the react hook. Before this change, that fails with an internal error inside the hook, where we assumed that the variables were present. If you pass `mutate({})`, things work fine, but that seems superfluous. The types should have caught this if we were working in TS, but since we were in the Gadget editor, the type check is off.
So, this changes the types and the runtime code to allow passing nothing at all to the mutate function returned by the hook if there are no required variables. We're still just the client here, so the server will still validate that any really required params are present and return an error if they aren't passed.
> Allow passing no mutation variables to the react hook

- packages/api-client-core/src/ClientOptions.ts
- packages/api-client-core/src/GadgetConnection.ts
This adds an `exchanges` parameter to our client constructor so we can add custom ones in the sandbox. I decided to go with 3 hooks (beforeAll, beforeAsync, afterAll) based on the docs below:
https://formidable.com/open-source/urql/docs/advanced/authoring-exchanges/#synchronous-first-asynchronous-last
This API doesn't give us complete control over the exchanges (e.g. re-arrange, remove, replace), so if you think we will want to do any of that we should add it now.
> Add `exchanges` option

- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/support.ts
We inadvertently changed the behaviour of the return value on bulk deletes with the Error group changes. This goes back to returning `undefined` instead of `[]`
> Bulk action return value

- packages/react/package.json
Failing dependency on the deep-equal package. Using this to override during an incident.
> change: resolution for deep-equal on react package

- packages/api-client-core/package.json
- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/package.json
- packages/react/src/useBulkAction.ts
Tiny type change and support for accepting bulk params. Tests to come in a second PR once Gadget proper creates clients with support for this
> Add support for bulk actions which accept params beyond just an ID

- .eslintrc.js
- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/blog-example/src/App.tsx
- packages/blog-example/src/main.tsx
- packages/react-shopify-app-bridge/spec/useGadget.spec.ts
- packages/react/spec/components/auth/SignedOut.spec.tsx
- packages/react/spec/jsdom-environment.ts
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useFetch.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/auth/useAuth.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useFetch.ts
- packages/tiny-graphql-query-compiler/spec/calls.spec.ts
- packages/tiny-graphql-query-compiler/spec/mutation.spec.ts
- packages/tiny-graphql-query-compiler/spec/query.spec.ts
After switching to ESM builds, extensions in import statements are important! Let's lint their existence. Also fixed a number of other latent lint warnings.
> Add import-extensions lint rules and fix latent lint warnings

- packages/api-client-core/spec/GadgetConnection.remote-ui.spec.ts
- packages/api-client-core/spec/remote-ui-environment.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/react/package.json
- packages/react/src/useStructuralMemo.ts
- pnpm-lock.yaml
Shopify's new extension functionality supports importing and running JS modules that make external API calls, in both checkout extensions and the new admin extensions. Gadget's client currently throws for two reasons when you try this though:
- Shopify's locked down extension environment (powered by [shopify/remote-ui](https://github.com/Shopify/remote-ui)) has a `globalThis.fetch`, but doesn't have a `globalThis.WebSocket`, which we expect to be present. It's absence is ok though -- extensions don't really need to open up transactions against Gadget and so don't need websockets. In a subscriptions/livequery-y future that'd change, but investing in a whole other transport is a lot of work. We can make normal reads and writes from an extension work just fine though by not requiring …
> Support weird shopify extensions context

- package.json
- packages/react/package.json
- packages/react/spec/auth/useSession.spec.ts
- packages/react/spec/auth/useUser.spec.ts
- packages/react/spec/useAction.spec.tsx
- packages/react/src/utils.ts
- pnpm-lock.yaml
`useAction` was nesting variables under the action model api identifier, but the graphql api for these actions were expecting them to be non-nested (`api.user.signUp({email..})` is not nested under `user` like it would be in `api.user.signUp({user: {email:...}`). This caused us to pass in the variables to graphql in a shape it was not expecting (and could not parse the data for)!
> Fix for useAction incorrectly mapping non nested auth action inputs

- packages/api-client-core/package.json
- packages/react/package.json
- pnpm-lock.yaml
Superseeds https://github.com/gadget-inc/js-clients/pull/266, resolves a security advisory when installing the client
> Bump graphql dependency to latest

- packages/react/spec/useFindFirst.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/utils.ts
urql hooks have a `pause` option that allows preventing sending the initial request. We should respect this option and pass it through to urql and avoid doing anything that requires never pausing a request.
> Ensure hook pausing with urql works

- packages/api-client-core/src/DataHydrator.ts
- packages/api-client-core/src/GadgetRecordList.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/types.ts
The InternalModelManager is public API for Gadget developers, so it should be well documented and have nice types for use inside the editor. We had `any`s everywhere when we can instead have nice types! This adds those.
> Add more complete types for the InternalModelManager

- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useBulkAction.spec.ts
- packages/react/src/utils.ts
Support for invoking bulk actions with flattened params in react was broken, and https://github.com/gadget-inc/js-clients/pull/267 accidentally broke it further.
It was broken since inception because the tests were asserting incorrectly that the produced `input` params weren't nested -- they should have been, oops! Updated the tests and stopped using snapshot tests to describe this so no one is tempted to break it.
Then, to fix the issue and properly disambiguate the params, I had to change the behaviour of the disambiguator a little bit. To preserve the behaviour for the change in https://github.com/gadget-inc/js-clients/pull/267, we need to respect the idea that if an action does not accept model input, we shouldn't do any nesting of variables. This does this by giving the new …
> Fix react bulk actions with flat params

- packages/api-client-core/package.json
- packages/api-client-core/spec/mockUrqlClient.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/types.ts
- packages/react/package.json
- packages/react/spec/jest.setup.ts
- packages/react/spec/liveQueries.spec.tsx
- packages/react/spec/testWrappers.tsx
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindFirst.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/utils.ts
- packages/react/src/utils.ts
- pnpm-lock.yaml
Using the `@live` query directive, we can ask Gadget to give us back a stream of data as it changes from the backend! We can use the graphql-ws transport we already have setup and productionized for this, and we can use urql's ability to rerender at will to trigger a nice rerender. To start, live queries are only available in the React hooks for rendering. 
Depends on https://github.com/gadget-inc/gadget/pull/8413 for the json diff patch format stuff.
> `@live` Queries

- packages/react/package.json
Support for `returnType` was added in `api-client-core` v0.15.4. We should update the `react` package's dependencies to be the latest for `api-client-core` so that it can leverage those features.
> bump @gadgetinc/api-client-core version in @gadgetinc/react dependencies

- package.json
- packages/api-client-core/spec/mockUrqlClient.ts
- packages/blog-example/src/App.tsx
- packages/react/package.json
- packages/react/spec/useFetch.spec.tsx
- packages/react/src/useFetch.ts
- pnpm-lock.yaml
This fixes a very subtle bug in `useFetch`. When running a fetch request with `shouldSendImmediately: false` and `json: true`, users would get an error looking like this:
```
Uncaught (in promise) ErrorWrapper: [GraphQL] The user aborted a request.
at _ErrorWrapper.forClientSideError (https://fetch-testing--development.gadget.app/node_modules/.vite/deps/@gadgetinc_react.js?v=19130701:484:12)
at dispatchError (https://fetch-testing--development.gadget.app/node_modules/.vite/deps/@gadgetinc_react.js?v=19130701:966:32)
at https://fetch-testing--development.gadget.app/node_modules/.vite/deps/@gadgetinc_react.js?v=19130701:1048:25
```
This is because the POST request was immediately, erroneously being aborted as soon as it was run. We don't want to abort the request, we want to run it!
We have …
> Fix support for POST requests run in strict mode from useFetch

- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/package.json
The Gadget client already knows how to talk websockets to the Gadget backend, but the custom auth mode we use in the React provider didn't have support for passing the Shopify JWT for this. Now it does!
> Add support for sending the shopify session token via websocket requests in the React provider

- packages/api-client-core/spec/mockUrqlClient.ts
- packages/react/package.json
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useActionForm.spec.tsx
- packages/react/src/index.ts
- packages/react/src/useAction.ts
- packages/react/src/useActionForm.ts
- packages/react/src/utils.ts
- pnpm-lock.yaml
This PR introduces `useActionForm` that will allow us to use `react-form-hook` together with `useAction`; this hook will help us create smaller starting files for our web apps. @airhorns this is mostly the code you wrote with a few changes:
- I'm not returning `modelManager` from the hook; let's leave it out for now and if we need it later add it in
- the hook returns `actionData`
- the promise returned when calling `submit` waits until the action has resolved
> introduces useActionForm

- package.json
- packages/react/spec/apis.ts
- packages/react/spec/auth/useAuth.spec.ts
- packages/react/spec/auth/useSession.spec.ts
- packages/react/spec/auth/useSignOut.spec.ts
- packages/react/spec/auth/useUser.spec.ts
- packages/react/spec/components/auth/SignedIn.spec.tsx
- packages/react/spec/components/auth/SignedInOrRedirect.spec.tsx
- packages/react/spec/components/auth/SignedOut.spec.tsx
- packages/react/spec/components/auth/SignedOutOrRedirect.spec.tsx
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useActionForm.spec.tsx
- packages/react/src/useActionForm.ts
- pnpm-lock.yaml
once https://github.com/gadget-inc/js-clients/pull/286 we found that the typing in our email password template had issues; this was mainly because we didn't add the server side validation types to `formState: {errors}` this PR adds that typing (I'm sorry it's so confusing 😢 ) to say that the server side validation errors can be any of the field values of the model or any of the variable keys.
There is one issue in that for reset password for the typing to work we need to have:
```
useActionForm<
(typeof fullAuthApi.user.resetPassword)["optionsType"],
(typeof fullAuthApi.user.resetPassword)["schemaType"],
typeof fullAuthApi.user.resetPassword,
{ confirmPassword?: string }
>(fullAuthApi.user.resetPassword, {
defaultValues: { code: "abc123" },
});
```
I'm not sure how we can do this typing …
> better typing for useActionForm

- packages/react/spec/components/auth/SignedInOrRedirect.spec.tsx
- packages/react/spec/components/auth/SignedOutOrRedirect.spec.tsx
- packages/react/spec/testWrappers.tsx
- packages/react/src/GadgetProvider.tsx
- packages/react/src/auth/SignedInOrRedirect.tsx
- packages/react/src/auth/SignedOutOrRedirect.tsx
- packages/react/src/auth/utils.ts
By default our components that control navigation `SignInOrRedirect`/`SignOutOrRedirect` use `window.location`. This causes window reloads and flashes of unstyled content. We can't make assumptions about an app's routing system, so we should allow consumers to pass in a custom navigate function that we'll use.
> Allow a custom navigate to be provided to the Provider

- packages/react/spec/auth/useAuth.spec.ts
- packages/react/src/auth/useAuth.ts
Users may need to access things like `signInPath`, `redirectOnSuccessfulSignInPath`, etc... in components. An example would be 
```typescript
<Link to={authConfig.signInPath} />
```
instead of needing to do
```typescript
<Link to={window.gadgetConfig.authentication.signInPath />
```
closes GGT-5051
> Add auth config to the object returned from useAuth

- packages/react/spec/auth/useSignOut.spec.ts
- packages/react/src/auth/useSignOut.ts
Missed `useSignout` when updating components to use the `navigate` prop
> update useSignout to also use navigate prop if possible

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/src/exchanges/urlParamExchange.ts
This is useful for gadget internally passing endpoints with existing query params to use for tagging, which we're gonna use for the consistent hashing business
> Add support for endpoints with existing query params

- packages/react/package.json
- pnpm-lock.yaml
This releases a new version of `@gadgetinc/react` that locks `react-hook-form` down to a version that supports node 16. We will allow users on Gadget version `0.1.0` to continue to install `@gadgetinc/react`
> pin react-hook-form to a version that supports node 16

- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/support.ts
This change implements handling rate limit errors on the GadgetConnection clientside communicating to the core Gadget API over websockets.  The  server sends a rate limit code and closes the websocket over the wire.
> add: rate limit error handling

- packages/api-client-core/package.json
- packages/api-client-core/src/AnyClient.ts
Small PR to merge in the required changes for handling nested relationships in the `react` library.
Going forward all clients have baked in relationship metadata that we use in the `react` library to reshape the data when passing it on to graphql.
> Added model relationships to AnyClient interface for upcoming support of nested relationships

- packages/api-client-core/src/ClientOptions.ts
- packages/api-client-core/src/GadgetConnection.ts
In an n-environment world we aren't limited to simply development and productions thus we should accept any string. We still handle normalizing the environments in gadget when generate the client so I think is fine to change.
closes GGT-5386
> Update environment type to string

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/spec/Provider.spec.tsx
- packages/react-shopify-app-bridge/spec/useGadget.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react-shopify-app-bridge/src/context.ts
- pnpm-lock.yaml
This updates `react-shopify-app-bridge` to support `@shopify/app-bridge-react` v4. Will run this through CI over in gadget before merging
> Shopify app bridge v4 support

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/spec/Provider.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
We should only throw this error if the app is embedded, missing app bridge, and we're embedded in shopify admin. Ran into some issues with cypress tests in gadget since cypress is also an iframe
> Throw only if app bridge undefined and embedded in admin

- packages/api-client-core/spec/mockActions.ts
- packages/api-client-core/spec/mockUrqlClient.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/BackgroundActionHandle.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/support.ts
- packages/react/src/useEnqueue.ts
Uses a subscription endpoint on gadget (https://github.com/gadget-inc/gadget/pull/10364) to get the background action result. 
We are waiting on the subscription for the first pushed result that either has an outcome set or contains an error (for example permission error) and processes the responses in the same way as the "api" version of the actions.
> Add an runner to get action results

- packages/api-client-core/src/BackgroundActionHandle.ts
- packages/api-client-core/src/operationRunners.ts
- packages/react/src/useEnqueue.ts
This removes the `options` parameter from `BackgroundActionHandle` which was previously accepting the options that the job was enqueued with. The parameter is not being used anywhere right now and is the same object that is called with `enqueue`. Having this parameter as required makes it harder to implement the construction of a handle from just an ID as the options are not necessarily known.
> Remove options parameter from BackgroundActionHandle

- packages/api-client-core/package.json
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/operationRunners.ts
Caught a case that I had broken with https://github.com/gadget-inc/js-clients/pull/322 where the result was not properly being accessed. Unfortunately this case where `hasReturnType` being true had no tests so was not caught during refactoring. 
I don't know if its possible to re-release the version; whether this happens automatically or I need to bump the version again.
> Fix result processing

- packages/api-client-core/package.json
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/types.ts
- packages/react/package.json
- packages/react/spec/useEnqueue.spec.tsx
Adds support for `startAt` option to enqueuing background actions to allow them to be scheduled into the future. This is already supported by the graphql api inside gadget. For convenience I am allowing both ISO strings and `Date` objects that will automatically be converted.
> Support startAt parameter to BackgroundActionOptions

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/spec/Provider.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
`window.top.href` throws an error if you try to access it cross origin so I think the best we can do is to check `document.referrer`. ran through ci in gadget
> use document.referrer instead of window.top

- packages/api-client-core/package.json
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/BackgroundActionHandle.ts
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/support.ts
- packages/react/package.json
- packages/react/spec/useEnqueue.spec.tsx
- packages/react/src/useEnqueue.ts
- packages/react/src/utils.ts
This updates our operation planners and runners to work with background enqueued bulk actions, which return an array of handles instead of just one.
> Add support for enqueuing actions in the background in bulk

- packages/api-client-core/package.json
- packages/api-client-core/spec/repeater.spec.ts
- packages/api-client-core/src/graphql-live-query-utils/createApplyLiveQueryPatch.ts
- packages/api-client-core/src/repeater/index.ts
- pnpm-lock.yaml
The repeater-lite code is moved to js-clients monorepo (api-client-core package) itself for easier maintenance.
Test cases passing:
Test Video with a prerelease version:
https://github.com/gadget-inc/js-clients/assets/25290212/ea6cd6bb-d0a0-4010-8d73-e148dd0075a3
> Remove Repeater dep

- packages/api-client-core/jest.config.js
- packages/api-client-core/package.json
- packages/api-client-core/spec/imports/cjs-import.js
- packages/api-client-core/spec/imports/named-esm-import.mjs
- packages/api-client-core/spec/jest.setup.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/react-shopify-app-bridge/package.json
- pnpm-lock.yaml
A user on discord reported that the way we import cross-fetch doesn't work in a native ESM context:
I can't reproduce it -- when I import `cross-fetch` in a native ESM context locally, I get a module with `fetch` and `default` defined, but I don't really care -- we need to work in next.js. This fixes that twice: first, by using `globalThis.fetch` for our fetch implementation if it is found, which in recent nodes, it is. We used to only check for `window.fetch`, but `globalThis.fetch` is a thing in node (and uses fancy caching smarts in next.js by default too). The second fix is to make the fallback to cross-fetch work if what is returned is a naked ESM module with just the `default` prop that we need to access. 
Yucky.
Annoyingly, the change to start using `globalThis.fetch` breaks our …
> Add support for using the `fetch` global from node, and for importing cross-fetch in ESM contexts

- packages/api-client-core/package.json
- packages/api-client-core/spec/mockUrqlClient.ts
- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/spec/Provider.spec.tsx
- packages/react-shopify-app-bridge/spec/useGadget.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-BelongsTo-relationship-with-support-for-Id-pre_1709343723/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-BelongsTo-relationship_3235963512/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-multiple-BelongsTo-relationship-with-support-f_3501493881/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-multiple-BelongsTo-relationship_1667904710/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-relationship_933332662/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-relationship_2952094097/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-relationship_3875503635/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-multiple-HasMany-HasMany-HasOne-relationships_2856696492/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-multiple-HasMany-HasMany-relationships_3250074585/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-multiple-HasMany-relationships_2510062961/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship-with-support-for-Id-prefix-test_2503398001/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship_3741776720/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasMany-Multiple-HasMany-relationship_4201319124/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasMany-relationship_2440118782/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasOne-relationship_3220970997/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships-that-are-reordered_1591436327/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships_1125172282/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-root-even-if-nested_698860812/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-root-object_3536142481/recording.har
- packages/react/spec/useActionFormNested.spec.tsx
- pnpm-lock.yaml
To support shopify managed installs I am changing our Shopify app bridge provider to do initial setup with an app by calling a mutation that may have as a side effect that a shop is installed as part of loading the app for the first time. We need to do this because with Shopify managed installation there is no prior communication with a Gadget app during the installation process and the first request to the Gadget backend will come the first time the app is loaded in an embedded context. This mutation will detect this scenario and will install the app Gadget side using a session token exchange
> handle shopify managed installation

- packages/api-client-core/package.json
- packages/api-client-core/spec/helpers.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/operationRunners.ts
- pnpm-lock.yaml
We shipped all the backend support for live queries and the frontend support to the react client only. This adds support to the helper functions we use within the imperative, non-react JS client for live queries also!
I chose to use async iterators for this api. Calls will look like this:
```typescript
for await (const widget of api.widget.findOne("123")) {
console.log(widget);
}
```
`widget` there is a fully formed `GadgetRecord` instance, and each time it changed on the backend, we push a whole new instance out the async iterator.
This async iterator approach is the smallest amount of code, and doesn't couple our external interface to any one library's interface for observables or event emitters or whatever. It just uses JS builtins (async iterators), and those can be adapted outside of …
> Add live query support to the imperative operation runners

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
made a big mistake in https://github.com/gadget-inc/js-clients/pull/373 where we only request a session token from the app bridge once when the provider mounts and then reuse that across it's lifetime; only issue: the token has a 60 second expiry :(
We need to request. a new token each time the client makes a request
> refresh session token on every request

- packages/api-client-core/package.json
- packages/api-client-core/spec/helpers.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/graphql-live-query-utils/index.ts
- packages/react/package.json
- packages/react/spec/liveQueries.spec.tsx
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindFirst.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/src/utils.ts
- packages/tiny-graphql-query-compiler/package.json
- packages/tiny-graphql-query-compiler/spec/helpers.ts
- pnpm-lock.yaml
Most Gadget users don't execute live queries, and the code to power them is kinda big, it's about 10% of our bundle size. To try to help folks keep their LCPs down, I think we should defer loading it until someone executes the first live query. It's a quick request for that JS at that time, and live queries are already set up to stream results, so the deferred loading can be managed pretty easily. 
While working on this, I also noticed that the live query utils were importing all of `graphql`! `urql` uses a slimmed down version of `graphql` internally called `@0no-co/graphql` that has a much smaller bundle size, and we were accidentally including both it and the mainline graphql via `graphql-live-query`. We were only using one very small function from the latter library, so I just …
> Dynamic import the live query implementation for smaller initial bundle size

- packages/api-client-core/package.json
- packages/react/package.json
> chore(client-core): bump api client core version to 0.15.22

- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/AnyClient.ts
- packages/api-client-core/src/GadgetRecordList.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/support.ts
- Use tiny-graphql-query-compiler for all dynamic internal queries
- Switch the internal model manager over to using tiny-graphql-query-builder
- Adds namespace support to all the generated queries within the internal model manager, as well as the types that it outputs
> Add namespace support to the internal model manager

- packages/api-client-core/package.json
A new version of api-client core that contains support for internal api namespacing and awaiting the result of a namespaced background action.
> chore(client-core): bump api client core version to 0.15.23

- packages/tiny-graphql-query-compiler/spec/query.spec.ts
- packages/tiny-graphql-query-compiler/src/index.ts
When we compile a FieldCall, we lift the variables up to the top level query inputs.
We handle the case where this happens to a subfield, but we're not handling the case where there is a subfield in the selection of a FieldCall itself which is also a FieldCall.
In that case, we were failing to contribute the variables of the subfield call during `extractVariables`
> fix(tiny-qql): lift field call subselect call variables

- package.json
- packages/react/package.json
- packages/react/spec/apis.ts
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useEnqueue.spec.tsx
- packages/react/spec/useFindBy.spec.ts
- packages/react/spec/useFindFirst.spec.ts
- packages/react/spec/useFindMany.spec.ts
- packages/react/spec/useFindOne.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useFindBy.ts
- packages/react/src/useFindFirst.ts
- packages/react/src/useFindMany.ts
- packages/react/src/useFindOne.ts
- packages/react/src/useMaybeFindFirst.ts
- packages/react/src/useMaybeFindOne.ts
- pnpm-lock.yaml
Adds tests for the functionality added to the react hooks in https://github.com/gadget-inc/js-clients/pull/353 that didn't have tests
> React hooks for namespaced models / global actions tests

- packages/tiny-graphql-query-compiler/package.json
Fixes this bug in tiny-gql-compiler's call parameters: https://github.com/gadget-inc/js-clients/pull/407/files
> Bump tiny-gql-version to 0.2.3

- packages/react/package.json
Bumping the `@gadgetinc/react` package version for the namespace support in react hooks introduced in https://github.com/gadget-inc/js-clients/pull/400
> Bump gadget react package version to 0.15.8

- packages/shopify-extensions/README.md
- packages/shopify-extensions/package.json
- packages/shopify-extensions/src/react/Provider.tsx
Looks like an extra `;` snuck into the Provider
It haunts me. I removed all semi colons from my sample app and tried an extensions sans-Gadget just to make sure
Also a small docs update
> remove the extra semicolon from the Provider component

- packages/api-client-core/package.json
- packages/api-client-core/spec/mockActions.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/BackgroundActionHandle.ts
- packages/api-client-core/src/operationRunners.ts
- packages/react/package.json
- packages/react/spec/useEnqueue.spec.tsx
- packages/react/src/useEnqueue.ts
- packages/react/src/utils.ts
Adds typing to background action handles that determines the result type based on the Action being passed in. This means that actions such as `MockWidgetCreateAction` will be typed as a `GadgetRecord`. I had to follow a similar pattern to what is in `useActionForm` and pass through a `SchemaT` type otherwise the typescript compiler complains when inferring the `GadgetRecord` shape. This type also has to be propagated back up into the `useEnqueue` react package in order to properly construct the correct `BackgroundHandle` and result type. 
I added additional typing to the `MockWidgetCreateAction` to better reflect the types that an actual action will have when constructed by gadget.
Note: I still need to test it with gadget codebase but that has been causing me some difficulties...
> Background action result types

- packages/api-client-core/spec/GadgetRecord.spec.ts
- packages/api-client-core/src/support.ts
There's a bug where GadgetRecord reports changes to fields when the object changed identity but not value. In the case of dates, this happens with assigning dates that are the same instant but from different moments in time, and in the case of BelongsTo fields, this happens when setting `record.shopId = { _link: "123" }`, when the prior value was just "123". In these instances, we change our definition of equality to ensure these are considered the same value.
For `Date` objects, this was actually already the case, so there must be another bug somewhere. I suspect what's happening Gadget side is the value is showing up on the record as a string, and so the special date comparison logic was not kicking in. This PR should fix the belongsto part of the bug for real though.
Partly fixes …
> Prevent semantically meaningless change reporting

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/spec/GadgetConnection.browser.spec.ts
- packages/api-client-core/spec/GadgetConnection.node.spec.ts
- packages/api-client-core/spec/GadgetConnection.remote-ui.spec.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/exchanges/urlParamExchange.ts
If the base websocket endpoint already had url params, the naive approach we were using before incorrectly appended `?` twice. This uses the browser builtin for adding url params that we actually already have code for to do so.
> Ensure adding more url params to a websocket endpoint correctly appends them

- packages/react/package.json
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship_3741776720/recording.har
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/utils.ts
This took me a lot longer than I'd like to admit to find the fix.
To summarize the issue.
If you used `useActionForm` with any update action alongside a model that had any type of `hasMany`/`hasManyThrough` relationship. And Attempted to register said relationship on a field array. A good example being: `sections` instead of  `widgets.sections`.
`reshapeDataForGraphql` could either return an invalid shape or worst would exclude the values you updated. The issue arose from `disambiguateDefaultValues` comparing against the original fetched results with edges and nodes.
> unwind initial data in disambiguateDefaultValues to fix invalid data

- packages/react/spec/auto/MockForm.tsx
- packages/react/spec/auto/hooks/useFieldMetadata.spec.tsx
- packages/react/spec/auto/inputs/PolarisBelongsToInput.spec.tsx
- packages/react/src/auto/hooks/useFieldMetadata.tsx
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisBelongsToInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisHasManyInput.tsx
- **UPDATE**
- Added a shared `useFieldMetadata` hook for commonly used process of turning a field api identifier into a path and field metadata
- This PR is a small subset of https://github.com/gadget-inc/js-clients/pull/423 - If that PR is blocked, this smaller PR can be merged so that other component work can be unblocked
- This PR before the other one or not at all
> add useFieldMetadata hook & context providers to MUI

- DEVELOPMENT.md
It was observed that using a `resolution` for `gitpkg`'d builds in Gadget apps would could cause an issue where the package used in the Gadget app would not match the contents of the `gitpkg`'d link. Using the link directly as a dependency seems to avoid this issue.
> Fix dev guide dependency instruction to avoid resolution bug

- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/operationRunners.ts
This PR fixes an issue of namespaced model not working when running `findBy...` operations like `findById` or `findBy{unique_field}`.
> Fix namespaced model not working for findBy... operation

- packages/api-client-core/package.json
Bump the version to apply the fix from https://github.com/gadget-inc/js-clients/pull/430
> Bump js-client-core to 0.15.25 for namespace fix

- packages/react/package.json
- packages/react/src/auto/polaris/PolarisDateTimePicker.tsx
- packages/react/src/auto/polaris/PolarisFileInput.tsx
- packages/react/src/auto/polaris/PolarisFixedOptionsCombobox.tsx
- pnpm-lock.yaml
- **UPDATES**
- The Shopify Polaris icons version used here was incompatible with the default Shopify Polaris icons version used in Gadget apps. This was due to a breaking change on their end caused by renaming icons
- References to the old icon names have been updated to the new replacement icons recommended by the Shopify docs
- Now, in Gadget apps, there is no need to change the default shopify dependencies in the Shopify template when adding the dependencies to use autoforms
> Update Shopify Polaris Icon dependency version

- packages/react/package.json
Bump the version to apply the fix from https://github.com/gadget-inc/js-clients/pull/434.
> Bump gadget react package to 0.15.12

- packages/react/spec/auto/PolarisAutoForm.stories.jsx
Fix the import path that is no longer correct after moving the files inside the folder.
> Fix incorrect import path in PolarisAutoForm storybook file

- packages/api-client-core/package.json
- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
Working on adding limit filtering on the session model, but `deleteMany` was broken because the session model does not take a `search` argument. I've made a change here that when generating the queries for internal deletes we don't add a variable to the query unless we are actually passing a variable.
I don't think always adding these variables in was intentional cc @airhorns
> only send query variables if they are defined

- packages/react/spec/auto/hooks/useFieldMetadata.spec.tsx
- packages/react/spec/auto/inputs/PolarisAutoHiddenInput.spec.tsx
- packages/react/spec/auto/inputs/PolarisBooleanIput.spec.tsx
- packages/react/spec/auto/support/helper.ts
- packages/react/spec/auto/support/widgetModel.ts
- packages/react/src/auto/hooks/useHiddenInput.tsx
- packages/react/src/auto/mui/index.ts
- packages/react/src/auto/mui/inputs/MUIAutoHiddenInput.tsx
- packages/react/src/auto/polaris/index.ts
- packages/react/src/auto/polaris/inputs/PolarisAutoHiddenInput.tsx
This PR introduces `AutoHiddenInput` for the auto component. Underneath is a `<input type="hidden">` for users to debug the value in a browser development tool.
> Implement hidden input for auto component

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/spec/auto/inputs/PolarisAutoHiddenInput.spec.tsx
- packages/react/spec/auto/support/gizmoModel.ts
- packages/react/spec/auto/support/shared.ts
- packages/react/spec/auto/support/widgetModel.ts
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/hooks/useHiddenInput.tsx
- packages/react/src/internal/gql/graphql.ts
- packages/react/src/useActionForm.ts
This PR excludes model fields that are not "dirty" when submitting the form. In the react-hook-form standard, a "dirty field" is a field the user has modified.
Previously, when the field was not dirty, its value was `null`. However, there is a semantic difference between `undefined` and `null`. If the field has a default value set in the Gadget editor and is not required, the backend cannot apply the default value to it.
By only including the dirty fields in the action parameters, excluded fields are considered `undefined`, and the backend can apply the default value to them.
> Exclude non-dirty fields when submitting an AutoForm

- packages/react/spec/auto/hooks/useFormFields.spec.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/metadata.tsx
- **UPDATES**
- Updated order of field appearance to match the `include` property
- Removed the `select` and `fields` properties, which seemed to duplicate the behaviour of the `include` and `exclude` properties
> Updated order of field appearance to match the `include` property

- .github/workflows/release.yml
- jest.config.js
- packages/react-big-commerce/jest.config.js
- packages/react-big-commerce/package.json
- packages/react-big-commerce/spec/Provider.spec.tsx
- packages/react-big-commerce/spec/are-the-types-wrong.spec.ts
- packages/react-big-commerce/spec/useGadget.spec.tsx
- packages/react-big-commerce/src/Provider.tsx
- packages/react-big-commerce/src/context.ts
- packages/react-big-commerce/src/index.ts
- packages/react-big-commerce/tsconfig.base.json
- packages/react-big-commerce/tsconfig.cjs.json
- packages/react-big-commerce/tsconfig.esm.json
- packages/react-big-commerce/tsconfig.json
- pnpm-lock.yaml
This adds a react provider for our BigCommerce connection. The provider has two jobs:
1. Set up the api client to use the session token passed in a query parameter that we will set when rendering big commerce apps using their `/load` callback and load the session to make sure that it is authenticated
2. If we are in an authenticated context initialize the BigCommerce sdk (this will be loaded on the entry html)
> react-big-commerce

- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/utils.ts
> filter out `__typename` when figuring out whether a belongsTo field needs a link

- packages/react-shopify-app-bridge/spec/Provider.spec.tsx
- packages/react-shopify-app-bridge/spec/useGadget.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react-shopify-app-bridge/src/global.d.ts
In order to lower app LCP, we want to avoid having to do a whole other roundtrip to the server every time the page loads to check the installed state of a shop. We need to do this in some circumstances -- for off-platform apps, or to trigger the install of a shop the very first time a shop using managed installs is seen. So, we can't just remove this request, but, we can avoid blocking on it if the backend says its ok to. The backend already needs to check install state when rendering the page in order to inject the right shopify api key, so we can have it pass a little bit more info about the install state when it does that.
> Add support for an install state hint passed from the server side to the client that allows the provider to fast-path

- packages/react/spec/auto/inputs/PolarisAutoPasswordInput.stories.jsx
- packages/react/src/validationSchema.tsx
- **UPDATE**
- Added frontend validations for passwords, url. email, and colors
- The regexes match those used in the main Gadget repo
- The url ad email validations come from `node_modules/yup/index.d.ts`
> Added strong password, url, email, and color validation

- packages/react/cypress/component/auto/form/PolarisDateTimePicker.cy.tsx
- packages/react/src/auto/polaris/inputs/PolarisDateTimePicker.tsx
The Polaris date picker is completely broken:
This PR fixes that, and patches some flaky tests.
Previously, it assumed the fieldProps.value must have a value. However, if the input has not been modified or has no default (e.g. when creating a record), fieldProps.value is actually null, making a date an "Invalid Date" and unable to render the calendar.
> Fix date picker

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/AutoFormContext.ts
- packages/react/src/auto/hooks/useResultBannerController.tsx
- packages/react/src/auto/index.tsx
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/mui/submit/MUISubmitResultBanner.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/submit/PolarisSubmitResultBanner.tsx
- packages/react/src/internal/gql/gql.ts
- packages/react/src/internal/gql/graphql.ts
- packages/react/src/metadata.tsx
- load the metadata from the new global action metadata endpoint
- update all the metadata thingies that derive data to use the global action input fields or the model action input fields
- use slightly different copy in the success banners for global actions, meriting a DRY'd up controller
- add some tests that hit both MUI and Polaris
> Autoforms for global actions

- packages/react/cypress/component/auto/form/PolarisAutoJSONInput.cy.tsx
- packages/react/spec/auto/inputs/PolarisAutoJSONInput.spec.tsx
- packages/react/spec/auto/inputs/PolarisJsonInput.stories.jsx
- packages/react/src/auto/hooks/useJSONInputController.tsx
- packages/react/src/auto/hooks/useStringInputController.tsx
- packages/react/src/auto/mui/inputs/MUIAutoJSONInput.tsx
- packages/react/src/auto/polaris/index.ts
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoJSONInput.tsx
- packages/react/src/validationSchema.tsx
Previously, the `useJSONInputController` was tracking its own error from invalid JSON inputs in its own `setState` call. This state was local to the component, so it didn't stop the form from being submitted. Instead, we need to store the error in the form state such that `react-hook-form` knows about it, and can revalidate using the validation schema. This implements that! It's still a little tricky because we need to store the raw input string the user is typing into and store the real JSON value in the form state so that it gets submitted. The controller now queues the validator that there has been a parse error by writing a special object indicating that there has been a parse error into the form state.
> JSON input error states

- packages/react/spec/auto/inputs/PolarisAutoDateTimePicker.spec.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoTimePicker.tsx
When a user presses the right or left arrow on the date picker popover, a new date is selected. 
https://github.com/gadget-inc/js-clients/assets/168455431/00b7750e-2f14-4abb-9117-30e7675029b7
This is because when the month was changed, the hook, `handleMonthChange` was modifying the variable that stored the date that the user had selected (`fieldProps`). This means that every time `handleMonthChange` was called, `fieldProps` would get redefined. 
The PR also fixes an issue where the time was reset to 12AM every time a user selected a new date.
> GGT-6724 - Fix month selection when month is paginated & Persist Time when Date Changes

- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/inputs/PolarisAutoPasswordInput.stories.jsx
- packages/react/spec/auto/inputs/PolarisBooleanInput.stories.jsx
- packages/react/spec/auto/inputs/PolarisFileInput.stories.jsx
- packages/react/spec/auto/inputs/PolarisJsonInput.stories.jsx
- packages/react/spec/auto/inputs/PolarisStringInput.stories.jsx
- **UPDATE**
- Previously, in storybook, the month did not appear in the date picker.
- This was because the 'ApProvider' did not have a "i18n' property passed into it
- Without the i18n, the date picker doesn't know if it should show `January | Janvier | يناير | 一月` etc...
- Now, English is explicitly passed in throughout the repo
> Add i18n to ShopifyPolaris app providers to get months into date pickers

- package.json
- packages/react/cypress/component/auto/form/PolarisAutoEnumInput.cy.tsx
- packages/react/spec/auto/inputs/PolarisAutoEnumInput.stories.jsx
- packages/react/spec/auto/support/stadiumModel.ts
- packages/react/src/auto/hooks/useEnumInputController.tsx
- packages/react/src/auto/mui/index.ts
- packages/react/src/auto/mui/inputs/MUIAutoEnumInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
- packages/react/src/auto/polaris/index.ts
- packages/react/src/auto/polaris/inputs/PolarisAutoEnumInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/validationSchema.tsx
- pnpm-lock.yaml
This PR introduces `AutoEnumInput` for the auto component.
When the input allows adding additional values, it provides an "Add ..." button, and when the input allows multiple selections, it becomes a multi-select dropdown.
The Polaris component version is based on the example from Polaris with modifications for our needs:
https://polaris.shopify.com/components/selection-and-input/combobox
> Implement enum input for auto component

- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/README.md
- packages/react/package.json
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship_3741776720/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasMany-Multiple-HasMany-relationship_4201319124/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasMany-relationship_2440118782/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships-that-are-reordered_1591436327/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships_1125172282/recording.har
- packages/react/spec/useActionForm.spec.tsx
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/types.ts
- packages/react/src/use-action-form/utils.ts
- packages/react/src/useActionForm.ts
- packages/react/src/utils.ts
This PR addresses a handful of shitty experiences a user in the discord had.
1. When updating a `belongsTo` relationship, you may want to update the link AND also display information returned from a `findby` associated with the child.
2. Send wasn't filtering out data being pushed into reshape
3. Adds the ability to mark fields as `ReadOnly` using a select which will be excluded from reshaping
> Add new behaviour for updating actions

- packages/react/src/validationSchema.tsx
Although we don't provide an array model field type, it's possible that people can define an array input type like this:
```js
export const params = {
p_arr: {type: "array", items: {type: "string"}},
}
```
Right now, If people have an action input with an array type, it throws an error when rendering the form. This PR prevents throwing an error and instead provides a generic array type.
> Include array type in field validator

- package.json
- packages/react/package.json
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/utils.ts
- pnpm-lock.yaml
To unblock @DevAOC. He ran into a broken edge case where he was updating multiple `belongsTo` relationships with an additional field in one model. The "additional field" would always be excluded improperly.
> fix belongsTo relationship linking with additional fields

- packages/react/cypress/component/auto/form/PolarisAutoFileInput.cy.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoFileInput.tsx
This PR fixes an issue when rendering the file input with size validation. It shows the "Accepts larger than xyz" when the validation is set to "min = undefined and max = xyz", which is incorrect.
> Swap the file size validation message

- packages/react/spec/useActionForm.spec.tsx
- packages/react/src/use-action-form/utils.ts
- packages/react/src/useActionForm.ts
The new data-masking functionality in `useActionForm` should be compatible with people using either shorthand field keys or longhand field keys for both create and update actions. This wasn't quite the case before for two reasons: we were only telling the data masker to try both keys for update actions, and we were only passing in pre-disambiguated data to try for update actions. This fixes both of those small issues and adds tests!
> useActionForm: ensure both shorthand and fully-qualified field names can be passed to send

- packages/react/src/auto/hooks/useFileInputController.tsx
Right now, in some rare situations, the file is not being removed when the user clicks the "delete file" button. This PR should fix this issue by setting the value to null instead of undefined.
> Set file value to null instead of undefined when clearing file

- packages/react/src/auto/hooks/useBelongsToInputController.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToInput.tsx
- **UPDATE**
- Previously, there was a bug with belongsTo fields on create actions where the label text would always be red
- The label should only be red when the current record's value does points to an ID that does not exist in the related model 
- The fix is to only do that check when there is a selected record with findBy
> Fixed belongsTo relationship component always having red label text for create actions

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/src/validationSchema.tsx
Right now, when you have a "required" validation error on the client-side, it will show this error like this:
```
model.field is a required field
```
This PR updates the error message to stop showing the raw dot notation path. Instead, the message will be like this:
> Update "required" validation error message to be more human readable

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/src/auto/AutoForm.ts
Right now, when you set fields to include using the `include` property in the AutoForm, none of the field values are sent. This PR fixes this issue. The details are in the comment below.
> Fix field values not being sent when having a "include" prop in the AutoForm

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/metadata.tsx
Right now, when the field has an invalid default value defined in the Gadget editor or any other errors, it throws a `no model metadata found from Gadget API` assertion error and not being able to render the whole page. However, it's unclear to the user that something went wrong when fetching the metadata to render the form.
This PR fixes this issue by showing the error banner when it fails to fetch the metadata due to an error and does not render the submit button. Note that this PR only handles the case where the user doesn't put children inside the `<AutoForm/>` component since we can't really control what the user is doing.
> Don't run assertion check when there is an error fetching metadata

- packages/react/src/auto/hooks/useRelatedModelOptions.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneInput.tsx
- **UPDATE**
- Previously, the onBlur callback for the relationship selector components would remove all of the existing options to replace them with the options on the first page, and this made it impossible to get option labels for the selected IDs that were outside of the first page.
- The original intention behind the removed callback was to save memory when the relationship dropdown pickers were blurred, but in retrospect, this would cause redundant re-fetching and the loss of option labels
- Now, the callback is removed, and  the options will remain loaded in the relationship picker component after blurring
> Fix relationship on blur pagination behavior

- packages/react/src/auto/polaris/PolarisAutoForm.tsx
Add better form input spacing, 16px vertical between each form input. 
I also noticed that we were wrapping the entire form body in a FormLayout component which I don't think is the intended use of that component -- it should be for grouping elements onto the same line.
> design(autoform): ensure 16px spacing between form elements

- packages/react/spec/auto/MockForm.tsx
- packages/react/spec/auto/inputs/PolarisAutoTextInput.spec.tsx
- packages/react/src/auto/hooks/useStringInputController.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoEnumInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoTextInput.tsx
Previously, we were using the `helpText` property for some Polaris inputs, but to get the nicely styled Polaris errors, we need to pass the error message to the `error` prop.
> fix(autoform): use polaris inline error messages

- packages/react/cypress/component/auto/form/PolarisAutoDateTimePicker.cy.tsx
- packages/react/cypress/support/commands.ts
- packages/react/cypress/support/cypress-commands.d.ts
- packages/react/src/auto/polaris/inputs/PolarisAutoTimePicker.tsx
We recently put the default field value into the form, but for the date time field type, the default value type is actually a string instead of a date, so it throws an error when there's a default value. This PR fixes it.
> Convert field value to Date in time picker

- packages/react/src/auto/polaris/inputs/PolarisAutoFileInput.tsx
Added a bit more padding around the 'trash' icon in the file upload input interface
> fix(autoform): 12px padding for trash icon in file upload input

- packages/react/src/auto/polaris/PolarisFixedOptionsCombobox.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoEnumInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneInput.tsx
When using vertical content + a prefix in the polaris combo box, the vertical alignment of the prefix icon can't be controlled easily to keep it vertically aligned with the placeholder text i.e. "Search", so it ends up looking bad. 
In the polaris docs examples, they either use vertical content + no prefix or they use a prefix and append tag pills below the input. 
According to @mike-briggs we should prefer the vertical content approach + no prefix.
> fix(autoform): remove search icon prefix from multiselects

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/mui/submit/MUISubmitResultBanner.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/submit/PolarisSubmitResultBanner.tsx
This PR introduces an `onSuccess` callback in the `<AutoForm />` component. We already have the same callback in our `useActionForm` so we only need to expose it as part of the available property in the React component.
The default banner will not be shown when the `onSuccess` callback exists, so people can override the behaviour.
> Introduce `onSuccess` callback in AutoForm

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/submit/PolarisAutoSubmit.tsx
Previously, a user would submit the form, and if a success/error banner did not immediately appear, they wouldn't know what state the form was in: is it a network issue? Is Gadget being slow processing the request? 
This PR adds a loading state to the submit button, so when the form is in the `isSubmitting` state, the button is greyed out, and a spinner appears:
> GGT-6756 Added spinner when a form is submitting

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/cypress/component/auto/form/AutoPasswordInput.cy.tsx
- packages/react/spec/auto/inputs/PolarisAutoPasswordInput.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoPasswordInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoPasswordInput.tsx
- **UPDATE**
- Previously, untouched password fields for update actions would result in a null value being sent to the DB
- Most other field types retrieve their record value from the DB and then send them back to the API through the form. Password fields are unique as their record value is not returned by the API, which means they can't send the same record value back to the API if untouched. That unknown record value then becomes null in the API request
- Sending null to the API will result in the password getting cleared from the record. Big security problem
> Prevent untouched password fields getting sent null values on update actions

- packages/react/cypress/support/auto.tsx
- packages/react/spec/imports/cjs-auto-import.js
- packages/react/spec/imports/esm-auto-import.mjs
- packages/react/src/auto/mui/index.ts
- packages/react/src/auto/mui/test-index.ts
The MUI autocomponents are not ready to be used by alpha testers, so they have been commented out in this PR.
> GGT-6770 - Temporarily removed the MUI autocomponents 

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/cypress/component/auto/form/AutoRoleInput.cy.tsx
- packages/react/src/auto/mui/inputs/MUIAutoRolesInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoRolesInput.tsx
- **UPDATE**
- Sometimes role list fields would not have loaded in options until you searched/unsearched
- This was because the options in `PolarisFixedOptionsCombobox` are initialized to the passed in options prop and those options were not loaded, thus leading to `PolarisFixedOptionsCombobox` getting initialized with an empty list of options 
- Now, we won't load the role picker component until options exist, thus we won't be stuck with a initially empty list use state
> Fix polaris role list options not loading initially until a search was conducted

- packages/react/src/auto/polaris/inputs/PolarisAutoTimePicker.tsx
The selected color for the custom time picker was different than the date picker, which made the form incohesive. 
This PR fixes that:
> Changed timer picker onHover color

- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- **UPDATE**
- Previously, dynamically changing the action or findBy value did not cause a re-render. This was a problem because you may end up thinking that you are editing the wrong value
- Now, changing the action or the findBy value will force a re-render, causing all of the fields to be reset to the defaults or the corresponding record values
> Added key to autoforms to make the contents re-render upon actions and findBy value changes

- packages/react/src/auto/hooks/useStringInputController.tsx
- **UPDATE**
- Previously, there was a console error when a null DB record value was passed to text fields. 
- Now, an empty string will be sent to the text inputs when there is a null DB value
- This does not trigger the controller's onChange function which will ensure that that value is still null if untouched when sent back to the API, thus leaving that record field unchanged
> Prevent null values for text input components

- packages/react/src/auto/hooks/useRoleInputController.tsx
- packages/react/src/use-action-form/utils.ts
- **UPDATE**
- PREVIOUSLY -> Race condition on the removed useEffect.
- If there was a findBy value corresponding to a record with roles and the submit button was pressed before the useEffect converted the returned role object list to a role key string list, there would be a type error since the API can only accept string arrays for role list fields
- This was only observed in tests, but would be more likely under conditions where the RolesMetadata comes has a much slower response than the other requests. 
- NOW 
- The useEffect has been removed and replaced with direct usage of `useController -> fieldProps.value`
- The retrieved record will have it's Role object array converted to a role key string array before it gets registered with the hooks
> Removed useEffect that caused a type error race condition on Role input components

- packages/react/cypress.config.ts
Ran this 10 times in a row and got the other cypress flake but not the failed to connect flake, I think this will improve things!
> Disable chrome gpu in CI to see if flakiness is reduced

- packages/react/cypress/component/auto/form/AutoPasswordInput.cy.tsx
This cypress test would occasionally flake due to the wrong request getting to the wrong test. My best guess is that this was caused by the intercept being un-awaited. I added an intercept awaiter, moved the intercept definition before the render, and added another check to ensure that the endpoint was called with the expected value
> Fix auto password input cypress test flake

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/cypress/component/auto/form/PolarisAutoRichTextInput.cy.tsx
- packages/react/cypress/support/DebugFormState.tsx
- packages/react/jest.config.js
- packages/react/package.json
- packages/react/spec/__mocks__/styleMock.js
- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/spec/jest-resolver.cjs
- packages/react/src/auto/hooks/useStringInputController.tsx
- packages/react/src/auto/hooks/utils.ts
- packages/react/src/auto/mui/inputs/MUIAutoBooleanInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoFileInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoFormControl.tsx
- packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoRichTextInput.tsx
- packages/react/src/auto/mui/styles/rich-text.css
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoRichTextInput.tsx
- packages/react/src/auto/polaris/styles/rich-text.css
- packages/react/src/auto/shared/AutoRichTextInput.tsx
- pnpm-lock.yaml
- uses https://mdxeditor.dev/editor/docs/getting-started which seems like a nice, medium weight markdown editor with lightweight customizability
- lazyloads this component using `React.lazy` for smaller default bundle size for autocomponents, as richtext is not often used that much
- wires up mdxeditor's base toolbar to show nice formatting buttons
- styles the rendered markdown using polaris css variables so that it matches kinda nicely in polaris
[no-changelog-required]
> Add a rich text input for autocomponents and apply nice polaris styling

- package.json
- packages/react/cypress/component/auto/table/PolarisAutoTableCellRenderer.cy.tsx
- packages/react/cypress/component/auto/table/PolarisAutoTableDateTimeCell.cy.tsx
- packages/react/cypress/component/auto/table/PolarisAutoTableFileCell.cy.tsx
- packages/react/cypress/component/auto/table/PolarisAutoTableTagCell.cy.tsx
- packages/react/cypress/component/auto/table/PolarisAutoTableTextCell.cy.tsx
- packages/react/package.json
- packages/react/spec/auto/MockTable.tsx
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableBooleanCell.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableCellRenderer.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableDateTimeCell.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableFileCell.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTablePasswordCell.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableTagCell.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableTextCell.tsx
- packages/react/src/metadata.tsx
- packages/react/src/useTable.tsx
- packages/react/src/utils.ts
- pnpm-lock.yaml
This PR does several things related to the AutoTable component:
- Introduces individual table cell renders for each supported field type
- Update the `getValue` function to return the raw value from a record
> Introduce table cell renderers for AutoTable

- packages/react/src/validationSchema.tsx
- **UPDATE**
- Previously, not having an input in a rich text field would block the request from sending due to a `required` validation being added regardless of if the field actually had a required validation on it or not
- Now, the having an untouched markdown field will only run a required validation if the Gadget field has a required validation on it
> Ensure required validation on richText fields only runs when the field has a required validation on it

- packages/react/spec/useList.spec.ts
- packages/react/src/useList.ts
A first pass at extracting a less 'table-y' version of a hook to co-ordinate the searching, filtering, paging, etc of a list of records. 
I will commit this and then refactor the useTable hook to use it in a separate PR rather than cause a bunch of merge conflicts with the currently inflight work.
> feat(autocomponents): extract useList from useTable for query controls

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/metadata.tsx
- packages/react/src/useTable.tsx
This PR introduces a new `useTable` property called `columns` that allows you to select a list of fields to include in a table. Right now, this property only accepts strings (field API identifiers) as a value inside the array. In the future, we will also take custom column renderers and pick a field for a relationship.
> Introduce `columns` property to select fields

- .github/workflows/test.yml
- packages/react/cypress.config.ts
I think we've given chrome a good chance -- the flakiness isn't worth it. Disabling until we find a solution.
> test(cypress): disable testing in real chrome browser

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
This PR shows a banner when there's a GraphQL error. It will look like this:
> Show banner inside the table when there is a GraphQL error

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
This PR introduces an `onClick` callback in the AutoTable component for users to customise the operation when clicking on a table row. The callback will provide the row record in the parameter.
> Introduce `onClick` callback in AutoTable

- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableCellRenderer.tsx
- packages/react/src/metadata.tsx
- packages/react/src/useTable.tsx
This PR adds the missing ID field to the AutoTable:
> Add ID field in AutoTable

- packages/react/spec/useList.spec.ts
- packages/react/src/useDebouncedSearch.tsx
- packages/react/src/useList.ts
- packages/react/src/useTable.tsx
A minor refactor to get useTable to consume the useList component.
> refactor(autotable): consume the useList hook in useTable

- packages/api-client-core/package.json
- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/spec/mockActions.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/support.ts
These changes will support introducing the upsert api to the js client. Mainly adds support for the case where an actions return type is a Union type.
> changes to api client core to support the upsert api

- packages/api-client-core/package.json
- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
In writing api tests for the internal upsert I realized I put an inconsistent call signature for the upsert between internal and public api. The fewer surprises the better so this moves the `on` param into the record payload of the internal call and pulls it out if its passed
> use consistent call signature for upsert between public and internal api

- packages/api-client-core/package.json
- packages/api-client-core/spec/TestSchema.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/operationRunners.ts
I made a type change to `ActionRunner` that seemed like it made sense in the context of the metadata client generation, but ended up breaking typechecking for the previous client generation strategy. This PR rolls back that type change and adds a test to make prevent this regression in the future
> ensure that legacy clients still typecheck correctly

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- **UPDATE**
- Exposed the `live` option from `useTable.useList.useFindMany` as a property in the `PolarisAutoTable` component so that the table can stay up to date with the real DB without refreshing the page
> Added live option to AutoTable props

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/src/auto/AutoForm.ts
- **UPDATE**
- Previously, passing in a bulk action to the Autoform would result in a `can't find metadata error`
- Now, we get `bulk actions are not supported` as an error message so the user can more easily identify where to fix the problem
> Added error message for passing bulk actions into the autoforms

- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/spec/humanizeCamelCase.spec.ts
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/utils.ts
- **UPDATE**
- Added humanized action names to forms 
- They are based on the GQL operation name, which is based on the API ID and the model
- Global actions get titles as well
- Action operation names containing numbers will keep the numbers beside each other 
- Ex: `Do99Things` -> `Do 99 Things`
- This only appears in one-liner AutoForms
> Added humanized action names to forms

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
Most of the scrolling behavior we want is already build into the polaris index table -- but we needed better container settings in the storybook to demonstrate it.
> chore(autotable-storybook): Better storybook container settings

- package.json
- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- pnpm-lock.yaml
This PR introduces an `onFailure` callback in the `<AutoForm />` component. We already have a similar callback called `onError` in our `useActionForm` so we only need to expose it as part of the available property in the React component.
The default banner will not be shown when the `onFailure` callback exists, so people can override the behaviour.
> Introduce `onFailure` callback in AutoForm

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/useTable.tsx
- packages/react/src/useTableUtils/helpers.ts
- packages/react/src/useTableUtils/types.ts
- packages/react/src/utils.ts
This PR adds support for having custom cell renderers in the `columns` property. By passing in an object like this:
```jsx
{
name: "some custom stuff",
render: (record) => <div>{record.name}</div>
}
```
it will render the column using the `render` function included in the object instead of using the default cell renderers.
> Introduce custom cell renderer in AutoTable

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/cypress/component/auto/form/AutoFormGlobalActions.cy.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/hooks/useHasManyInputController.tsx
- packages/react/src/auto/hooks/useJSONInputController.tsx
- **UPDATE**
- Added a field value resetting system that runs upon successful completion of create and global actions
- Some state based inputs had to get updates such that their input values would stay in sync with the overall hook context
- Inputs shall be untouched on errors
- Passing in an `onSuccess` property will avoid this behaviour
> Added system to clear form fields upon successful action submission for create and update actions

- package.json
- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/hooks/useFormFields.spec.tsx
- packages/react/src/auto/AutoForm.ts
- pnpm-lock.yaml
- **UPDATE**
- Added an error for custom params with api IDs that collide with model fields
- Why make an error? 
- `<AutoInput field={"fieldApiId} />` does a contextual api Id based lookup to through the action metadata to find out which one it should correspond to. 
- To discriminate between a model field and an action custom param, we would need...
- A: Another component property to ALL auto inputs that can collide with modelFIelds
- B: Force the user to use path like `modelA.field`. 
- More complexity for EVERYONE when this is a really rare use case
- The automatic labeling is based on API id and would result in duplicately named inputs. Confusing
- `include`/`exclude` would need some changes in order to discriminate between modelFields vs customParams
- The way that useActionForm …
> Added error for custom params colliding with model fields

- packages/react/cypress/support/component.tsx
- packages/react/package.json
- packages/react/spec/are-the-types-wrong.spec.ts
- packages/react/spec/imports/example-vite-project/index.html
- packages/react/spec/imports/example-vite-project/main.js
- packages/react/spec/imports/example-vite-project/package.json
- packages/react/spec/imports/imports-vite-project.spec.ts
- packages/react/src/auto/polaris/PolarisAutoButton.tsx
- packages/react/src/type-extensions/libnpmpack.d.ts
- pnpm-lock.yaml
We allowed a few packaging issues to slip through, which caused errors when importing from @gadgetinc/react/auto.
This fixes a few of those depednency issues and introduces an integration test which pacakges and installs @gadgetinc/react in a new vite project and imports AutoForm.
> fix(autocomponents): fix up package dependencies + add vite int. test

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/src/auto/mui/submit/MUISubmitResultBanner.tsx
- packages/react/src/auto/polaris/submit/PolarisSubmitResultBanner.tsx
- **UPDATE**
- It was previously impossible to close submission result banners for autoforms
- This was because of different instances of the same hook being used in the base banner component
- Updated to ensure that each banner only uses one hook
- Added test to ensure that the banners are closable
> Fix autoform banner closability

- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableTagCell.tsx
As the title suggests, this PR truncates the tags when they overflow in the UI or there are more than five tags.
> Truncate tags when overflow in AutoTable

- packages/react/src/index.ts
The `useList` & `useTable` hooks were not exported by accident, this is a two-line change that exports these hooks so that users can use the headless versions of autocomponents.
> Exported useList & useTable hooks

- packages/react/cypress/component/auto/table/AutoTableSort.cy.tsx
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
A test is missing from #534. It is added in this PR.
It ensures that when a sort prop is included in AutoTable, the correct column is sorted.
> Cypress test to ensure explicit sort is handled correctly

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- **UPDATE**
- Similar to the AutoForm, dynamically changing the input model would cause errors since some of the memoized stuff would still be associated with the old model
- Updated such that dynamically changing the model will completely re-render the whole table 👍 
- This was done in the same way as the form where a wrapper passing in a key surrounds the whole component content
> Fix dynamic model changes in autoTables

- packages/react/cypress/component/auto/table/AutoTableBulkActions.cy.tsx
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/hooks/useTableBulkActions.tsx
- packages/react/src/auto/polaris/PolarisAutoBulkActionModal.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/useTableUtils/types.ts
- **UPDATE**
- The bulk action system has been updated to allow for custom callbacks and renderers
- Custom renderers
- Similar to the cell renderer, the user can now pass in a React component returning function that takes in record IDs and the full records.
- POTENTIAL USE CASES
- Using IDs to power a useBulkAction or other Gadget hooks 
- Taking the records and doing an operation on their values. Ex: Showing the sum of all records on a particular field
- Custom callbacks 
- Similar to the custom renderer, runs the given callback with the selectedIds and selectedRecords and then shows the result of the callback in the modal 
- This could be useful so that users don't need to make a whole react component, but debatable if this is redundant with the custom renderer. 
- An `excludeActions` …
> Added custom bulk action callback and render system

- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/inputs/PolarisAutoTextInput.spec.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoNumberInput.tsx
- **Previously**
- The up/down spinner buttons in number field inputs did not work when number fields did not have a defined `decimals` value
- This was because we defaulted their step to "any". We did this to avoid the default `step={1}` which would sometimes erroneously cause a `must be an integer` error when the field would accept decimals 
- **Now**
- The step is set dynamically to match the current value in the input if there is no decimal count from the field configuration 
- **Things to test**
- UpDown spinner buttons on number inputs work
- Using decimals and the UpDown spinner buttons will change the highest precision decimal 
- UpDown arrow keys will be similar to clicking the UpDown spinner buttons, but they will not add trailing zeros
- This basically incrementally increases …
> Fixed AutoForm number input spinner button usage

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
This PR introduces two new parameters in AutoTable, `search` and `paginate`, which allow you to hide the search bar and pagination buttons by setting them as `false`.
Fixes GGT-6881, GGT-6882
> Allow hiding searching and/or pagination in AutoTable

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
The AutoForm component under test here is doing a React.lazy suspense,
and for some reason, it seems that possibly using the `screen` findBy
api results in a more reliable test result.
> fix(autoform): fix testing flake waiting for lazy load suspense

- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/useTable.tsx
- packages/react/src/useTableUtils/types.ts
In order to pass around all the sort callbacks to the TableContext, it would be easier if the sort state was in the useTable hook.
> refactor(autotable): move sort state into useTable hook

- packages/react/cypress/component/auto/table/PolarisAutoTableCellRenderer.cy.tsx
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableCellRenderer.tsx
- packages/react/src/useTableUtils/helpers.ts
- packages/react/src/useTableUtils/types.ts
In advance of switching over to a path notation for relationship fields, I think it makes sense to make some changes to the way the useTable rows and columns works. Right now, rows is mostly a representation of the record response, and the columns data structure hold a lot of information about i.e. the relationship and related model fields. 
Whatever is consuming the useTable has to implement some logic to i.e. extract the correct data from the edges/node type relationship gql response. 
After this change, that job is moved into the useTable hook, and `rows` now includes a more direct representation of what you would end up seeing in the final table (i.e. if a hasMany fields, the row entry would contain 'fieldName': ['first', 'second', 'third'] rather than a gql style edges/node data …
> Refactor rows and columns

- packages/react/cypress/component/auto/form/AutoFormTitles.cy.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- **UPDATE**
- Previously there was no way to control the title of the autoForm
- This control has been added. If it is not given then the humanized operation name will be used as the default
- Passing in an empty string will make it such that there is no title element rendered at all because the rendering it with an empty string will create some extra spacing
> Add customizable title control to AutoForm

- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/StorybookErrorBoundary.tsx
Using the existing `"react-error-boundary"` library, an error boundary has been added to surround the storybook entries
> Added error boundary to storybook

- packages/react/cypress/component/auto/table/AutoTableBulkActions.cy.tsx
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/table/PolarisAutoTableActions.stories.jsx
- packages/react/src/auto/hooks/useTableBulkActions.tsx
- packages/react/src/auto/polaris/PolarisAutoBulkActionModal.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/useTableUtils/types.ts
- **UPDATES TO ACTIONS PROP**
- Added optional `promoted` property so that actions can be accessed without clicking on the `more actions` button
- Custom actions are by default promoted to false where actions will be put into the dropdown menu
- Gadget model actions are promoted by default
- renamed `callback` to `action`
- Added `action: function | string` so that it is now possible to relabel Gadget bulk actions
> Update AutoTable actions api signature and add promoted actions system

- packages/react/cypress/component/auto/table/PolarisAutoTableDateTimeCell.cy.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableCellRenderer.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableDateTimeCell.tsx
- packages/react/src/useTableUtils/helpers.ts
- packages/react/src/useTableUtils/types.ts
- **UPDATE**
- DateTime fields with `includeTime:false` will now only show the date
- Showing the time requires that `includeTime:true` || `includeTime: undefined`
> Prevent showing time for dateTime fields with `includeTime:false`

- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/src/useTableUtils/helpers.tsx
Previously, passing the JSX element into the custom cell renderer's `render` function was impossible when a hook was inside. This PR fixes that by treating the `render` property as a JSX element and invoking it in a JSX style. 
Fixes GGT-6904
> Switch how we call `render` function to a JSX style

- package.json
- packages/react/cypress/component/auto/table/AutoTableSort.cy.tsx
- packages/react/spec/apis.ts
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/src/useTableUtils/helpers.tsx
- pnpm-lock.yaml
Some model fields are unavailable to query but are still included in the GadgetMeta response. This PR uses the `defaultSelection` instead to build the `targetColumns` array.
Fixes GGT-6903
> Use default selection when `columns` property does not exist

- packages/react/spec/imports/example-vite-base-react-project/index.html
- packages/react/spec/imports/example-vite-base-react-project/main.js
- packages/react/spec/imports/example-vite-base-react-project/package.json
- packages/react/spec/imports/imports-vite-project.spec.ts
- packages/react/src/useSelectedRecordsController.tsx
We accidentally relied on a Polaris type import when building one of the base hooks, which results in an error when consuming from a project that doesn't have Polaris installed. 
Also added a new test to confirm that importing the base @gadgetinc/react components works without Polaris installed.
> fix(auto-table): remove accidental polaris import from useTable hooks

- packages/react/cypress/component/auto/table/AutoTableContext.cy.tsx
- packages/react/cypress/component/auto/table/AutoTableSearch.cy.tsx
- packages/react/cypress/component/auto/table/helpers.ts
- packages/react/cypress/component/auto/table/metadata/widgetMetadata.ts
- packages/react/src/auto/AutoTableContext.ts
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/useTableUtils/helpers.tsx
- packages/react/src/useTableUtils/types.ts
In order to enable maximum flexibility for custom cell renderers, there is now a AutoTableContext and useAutoTableContext hook which basically returns everything that useTable() returns. 
You can access this in your component to trigger search actions, get pagination information, or access the raw data across records/rows.
> feat(autotable): Add a useTableContext hook for custom cell rendering

- packages/react/package.json
- packages/react/src/auth/SignedInOrRedirect.tsx
blerg React.StrictMode doesn't like when you useState to change how the flow of double invoked useEffects :(
> fix issue with signed in or redirect redirect

- packages/react/.changeset/moody-bees-hide.md
- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/hooks/useFormFields.spec.tsx
- packages/react/src/metadata.tsx
- **UPDATE**
- Previously, when a create action did not have required model fields due to `include` / `exclude` options, there would be an error that prevents the usage of the AutoForm
- This did not account for the possibility of action files setting the field values in the code instead of directly using the form value
- Updated such that required fields can be excluded from the autoform 
- Added an error to AutoForm when using `include` and `exclude` at the same time which aligns with the similar error in AutoTable
> Updated AutoForm such that required fields can be excluded

- packages/react/.changeset/chilled-drinks-mate.md
- packages/react/src/auto/polaris/submit/PolarisAutoSubmit.tsx
- **UPDATE**
- Previously, we did not expose the Polaris button props on the PolarisAutoSubmitButton component. Now we can
> Expose button props on Polaris auto submit

- packages/react/.changeset/little-bikes-dress.md
- packages/react/cypress/component/auto/form/AutoFormUpsertAction.cy.tsx
- packages/react/cypress/component/auto/form/AutoRoleInput.cy.tsx
- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/mui/inputs/MUIAutoIdInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoIdInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/metadata.tsx
- **UPDATE**
- Added upsert support to AutoForm
- When findBy is passed in 
- Is effectively an update action, but will create a record if given the ID that does not exist
- Does not clear inputs upon submission
- Without findBy
- An ID field input will be rendered allowing users to set the ID
- Clears all inputs upon submit
- **OTHER CONSIDERATIONS**
- Consider if/how the `on` field in upsert actions should work in fields. Currently unsupported
> Added Upsert support in AutoForm

- packages/react-shopify-app-bridge/spec/Provider-windowless.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/spec/GadgetProvider-windowless.spec.tsx
Currently, we use the `window.location` object to determine if the connection and set-up are ready. However, in some SSR frameworks like Remix.js, the `window` object is undefined, and instead, the `useLocation` hook is needed to access the location object.
This PR accepts passing the location object to our Shopify app provider and other fixes related to using the `window` object to enhance SSR support.
Example use case for a Remix.js app:
```jsx
// In root.jsx file
export default function App() {
const location = useLocation();  // <-- create a location object
return (
<html lang="en">
<body>
<AppProvider i18n={enTranslations}>
<GadgetProvider
type={AppType.Embedded}
shopifyApiKey={shopifyApiKey}
api={new Client({ environment: "development" })}
location={location}  // <-- then pass that …
```
> Accept location object when initialising GadgetProvider for SSR support

- packages/react-shopify-app-bridge/package.json
This PR bumps the `@gadgetinc/react-shopify-app-bridge` package to v0.16.1, which includes better SSR support.
- https://github.com/gadget-inc/js-clients/pull/606
> Bump react-shopify-app-bridge version to v0.16.1

- packages/react/.changeset/kind-lies-draw.md
- packages/react/cypress/component/auto/table/PolarisAutoTableTagCell.cy.tsx
- packages/react/src/auto/polaris/tableCells/PolarisAutoTableTagCell.tsx
- packages/react/src/utils.ts
When checking to see if something was a RoleAssignment list when rendering tags, we didn't handle the case where not only could the value be `null`, but it could also be an array with `nulls` in the array, leading to a runtime error when that happened.
> fix(react): handle when hasMany relationship has null value

- packages/react/.changeset/nervous-bobcats-smoke.md
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- **UPDATE**
- This button would erroneously appear on slender parent component widths. Disabled with the boolean flag on `<IndexFilter>`
- ![CleanShot 2024-08-26 at 14 40 59](https://github.com/user-attachments/assets/dc257edb-0d85-43d8-8c17-284d0534776b)
> Fixed bug in Polaris AutoTable where the `createNewView` button would erroneously appear on certain parent element widths

- packages/api-client-core/package.json
- packages/api-client-core/spec/InternalModelManager.spec.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/support.ts
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-BelongsTo-relationship-with-support-for-Id-pre_1709343723/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-BelongsTo-relationship_3235963512/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-multiple-BelongsTo-relationship-with-support-f_3501493881/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-multiple-BelongsTo-relationship_1667904710/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-HasOne-relationship_933332662/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-HasMany-relationship_2952094097/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-a-single-HasMany-relationship_3875503635/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-multiple-HasMany-HasMany-HasOne-relationships_2856696492/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-multiple-HasMany-HasMany-relationships_3250074585/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-create-multiple-HasMany-relationships_2510062961/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship-with-support-for-Id-prefix-test_2503398001/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship_3741776720/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasMany-Multiple-HasMany-relationship_4201319124/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasMany-relationship_2440118782/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-HasOne-relationship_3220970997/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships-that-are-reordered_1591436327/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships_1125172282/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-root-even-if-nested_698860812/recording.har
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-root-object_3536142481/recording.har
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useBulkAction.spec.ts
- packages/react/spec/useGlobalAction.spec.ts
I was working on formatting errors that come back from the imperative api and noticed that `InvalidRecordErrors` never had `modelApiIdentifier` set, even though it is on the type; turns out we just weren't selecting it in the operationRunners
This also adds a support function `formatErrorMessages` that takes GadgetErrors and turns them into nice structured objects for displaying error messages 
Forgive the large diff, it's snapshot changes now that we have changed the gql queries everywhere
~Also I've bumped all the other clients that depend on api-client-core so that if someone upgrades all gadget managed packages they will all ask for the same api client core version~
because of one of the react tests I need to release the new api-core-version first; I'll do that now and then follow up …
> Js client format errors

- packages/api-client-core/package.json
- packages/api-client-core/src/support.ts
`instanceOf` is not working well when importing this function in the sandbox; this makes `formatErrorMessages` more portable across different js contexts
> makes formatErrorMessages more portable across different js contexts

- packages/react-bigcommerce/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- packages/shopify-extensions/package.json
bump dependent clients after https://github.com/gadget-inc/js-clients/pull/624
> bump client versions for new api-client-core

- packages/react/.changeset/kind-plants-rule.md
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/src/useTable.tsx
- UPDATE
- Updated useTable `select` property to override default selection instead of merging with it
- This is a breaking change for those who are using `select` property and are relying on the default values merged into it
> Updated useTable `select` property to override default selection instead of merging with it

- packages/react/.changeset/moody-tips-do.md
- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/src/auto/AutoFormActionValidators.ts
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- **UPDATE**
- Updated the error message for passing in non-actions to be more explicit in describing that AutoForm needs valid Gadget actions with API triggers
AGMD-48
> Update AutoForm error messages for bad actions

- packages/react/.changeset/loud-balloons-cough.md
- packages/react/cypress/component/auto/table/PolarisAutoTableCellRenderer.cy.tsx
- packages/react/spec/auto/PolarisAutoTable.stories.jsx
- packages/react/spec/auto/hooks/helpers.spec.ts
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/use-table/helpers.tsx
- packages/react/src/use-table/types.ts
- packages/react/src/useTable.tsx
- **UPDATE**
- Columns with custom cell renderers were previously added to a record with the header as the key
- If duplicate custom cell headers were used, the earliest custom cell renderers would be overwritten due to the duplicate header used as a record key
- Now, the custom cell renderer index is incorporated into the record key, thus duplicate header named custom cell renderers no longer overwrite each other
> Fixed a bug with AutoTable where custom cell renderers with duplicate headers would have duplicate columns content

- packages/react/.changeset/perfect-cherries-grab.md
- packages/react/src/auto/AutoFormContext.ts
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/mui/submit/MUIAutoSubmit.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/submit/PolarisAutoSubmit.tsx
- **UPDATE**
- Previously
- Having `AutoSubmit` as a child of an AutoForm would not show the spinner while the form was submitting
- This was because that functionality was controlled by a prop in the one-liner approach
- NOW
- `AutoSubmit` has its loading state controlled by a hook thus it will properly show the spinner while it is submitting
- The state can be overridden if desired
> Context based loading spinner on AutoSubmit in AutoForm

- packages/api-client-core/src/AnyClient.ts
- packages/api-client-core/src/GadgetFunctions.ts
We want to remove the dependency from @gadgetinc/react -> api-client-core, because it's really easy to end up with multiple incompatible versions of api client core installed.
A main reason for the dependency is that @gadgetinc/react needs to access the operationBuilder functions in order to create query plans to pass to urql in hooks.
This PR attaches the plan builder functions as part of the action function prototype, alongside the other metadata about the action that is already present in the prototype.
This PR is a chain, currently consisting of:
1. This change to js-clients to introduce the plan to the types
2. This change to add the plan functions to the client instance when building it: https://github.com/gadget-inc/gadget/pull/12843
3. [in progress] having the react hooks consume …
> refactor(api-client-core): add operation builder plans to types

- packages/react/.changeset/red-wombats-share.md
- packages/react/cypress/component/auto/form/AutoFormDefaultValues.cy.tsx
- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/utils.ts
- PREVIOUSLY
- AutoForm `include/exclude` props would filter out what would be sent in the submission request. This filtering would apply to explicit passed in default values, making it impossible to set a non-editable default value
- NOW
- The `defaultValues` property will be used in the request regardless of the `include` / `exclude` properties
> AutoForm `defaultValues` included in request if not included in include/exclude

- packages/react-bigcommerce/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/.changeset/kind-plants-rule.md
- packages/react/.changeset/loud-balloons-cough.md
- packages/react/.changeset/moody-tips-do.md
- packages/react/.changeset/nervous-bobcats-smoke.md
- packages/react/.changeset/perfect-cherries-grab.md
- packages/react/.changeset/red-wombats-share.md
- packages/react/.changeset/silent-lobsters-promise.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/shopify-extensions/package.json
Releasing the next version of @gadgetinc/react
Note that the version boost for the peer dependency on the other packages should not affect any of their behaviour. They don't have any references to AutoComponent stuff, thus they can't be affected by the breaking changes
> Release @gadgetinc/react v0.17.0

- package.json
- packages/react/.changeset/rich-melons-decide.md
- packages/react/spec/useActionForm.spec.tsx
- packages/react/src/use-action-form/utils.ts
If you use useActionForm and select some fields from a relationship field and tag them as ReadOnly, it will still try to submit an empty value to the relationship field.
If your relationship field contains only ReadOnly values, it will consider the relationship field ReadOnly as well.
> fix(use-action-form): relationships that have only readonly fields

- packages/react/.changeset/blue-bears-float.md
- packages/react/cypress/component/auto/table/AutoTableBulkActions.cy.tsx
- packages/react/spec/auto/table/PolarisAutoTableActions.stories.jsx
- packages/react/src/auto/polaris/PolarisAutoBulkActionModal.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- UPDATE
- After talking to design, it was decided that we would use a toast system to indicate the result of running actions in AutoTable instead of having a multi-state modal system
- Updated `AutoTable` to automatically deselect records and close after running Gadget bulk actions
> Updated `AutoTable` to automatically deselect records and close after running Gadget bulk actions

- packages/react/.changeset/clean-flies-provide.md
- packages/react/cypress/component/auto/form/AutoFormInputLabels.cy.tsx
- packages/react/src/auto/interfaces/AutoRelationshipInputProps.tsx
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/mui/inputs/MUIAutoBooleanInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoDateTimePicker.tsx
- packages/react/src/auto/mui/inputs/MUIAutoEnumInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoFileInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoFormControl.tsx
- packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoJSONInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoRolesInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoTextInput.tsx
- packages/react/src/auto/mui/inputs/relationships/MUIAutoBelongsToInput.tsx
- packages/react/src/auto/mui/inputs/relationships/MUIAutoHasManyInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoBooleanInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoEnumInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoIdInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoJSONInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoRichTextInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoRolesInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoTextInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyInput.tsx
- packages/react/src/auto/shared/AutoRichTextInput.tsx
- Updated `AutoInput` to accept an optional `label?: string` input
- In many cases, I needed to explicitly put it later in a React element so that the prop would not be overridden by the default. 
- Any label you pass in explicitly should always be used by the AutoInput
> Updated `AutoInput` to accept an optional `label?: string` input

- packages/react/.changeset/nasty-crews-beam.md
- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/spec/auto/PolarisAutoForm.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/validationSchema.tsx
- PREVIOUSLY
- If you have a required field on a model action and it was hidden from the AutoForm with `include` or `exclude`, the form could not be submitted
- This was due to the required validation applying to the field 
- This issue did not have a corresponding error message
- NOW
- Input field validations are now only run on the fields that are shown when using `include` and `exclude`
- If a required field is excluded, the validation will occur server side, which allows for the field to be set in the model action code
> Fixed bug with AutoForm include/exclude system which prevented submission due to validations getting applied to hidden fields

- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useGlobalAction.ts
This PR sends a dev harness event when the action is a stubbed action (i.e. no API trigger)
Gadget side to consume this new event type: https://github.com/gadget-inc/gadget/pull/12894
> Send dev harness event from react hook when it is a stubbed action

- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/spec/useAction.spec.tsx
- packages/react/spec/useGlobalAction.spec.ts
- packages/react/src/useAction.ts
- packages/react/src/useBulkAction.ts
- packages/react/src/useGlobalAction.ts
This fixes bug introduced in https://github.com/gadget-inc/js-clients/pull/638 where a wrong action API identifier being sent when it is a bulk action.
> Add functionName and actionApiIdentifier when sending stubbed action event

- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
```jsx
const X = () => {
const [useFindBy1, setUseFindBy1] = useState(true);
return (
<>
<button onClick={() => setUseFindBy1(!useFindBy1)}>Toggle Find By</button>
<PolarisAutoForm action={api.widget.upsert} findBy={{ id: useFindBy1 ? "1" : "999" }}></PolarisAutoForm>
</>
);
};
```
- **UPDATE**
- Given something like the above component, we previously did not re-render the component upon dynamically changing the findBy object. 
- This was the result of the AutoForm key containing `[Object object]` for the find by value. Dynamic changes were lost to the simple `toString`
- Now, the key is based on a `JSON.stringify` of the findBy object/string
> fixed AutoForm not updating upon changes to findBy objects

- packages/react/.changeset/eight-pans-beg.md
- packages/react/.changeset/fair-files-repair.md
- packages/react/cypress/component/auto/table/AutoTableBulkActions.cy.tsx
- packages/react/src/auto/polaris/PolarisAutoBulkActionModal.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- Previously, the toast system for bulk action completion in AutoTable required a `Frame` wrapper to house the Toast component. This `Frame` unfortunately had some extra side effects that would cause the table to take on extra height, disrupting existing app user interfaces
- The frame component has been removed and the toast based bulk action feedback system has been reverted to the banner in modal approach
> Removed deprecated Polaris `Frame` usage from AutoTable

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/spec/auto/form/PolarisAutoFormErrors.stories.jsx
- packages/react/spec/auto/table/PolarisAutoTable.spec.tsx
- packages/react/src/auto/AutoFormActionValidators.ts
- packages/react/src/auto/AutoTableValidators.ts
- packages/react/src/auto/hooks/useTableBulkActions.tsx
- packages/react/src/auto/mui/MUIAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/useTable.tsx
This PR updates the error message when an invalid model or action is passed to AutoForm or AutoTable.
> Update auto component error messages

- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/polaris/index.ts
We already export the PolarisAutoForm component as AutoForm from the auto/polaris/index.ts file. We were accidentally also exporting it as PolarisAutoForm, which is a bit confusing for onlookers like the AI. Let's just export it once under a canonical name!
I also changed the skeleton to be explicitly exported as well using the existing naming convention.
> Don't re-export PolarisAutoForm as PolarisAutoForm

- packages/react/.changeset/late-dogs-talk.md
- packages/react/src/auto/AutoTable.tsx
- Added proper Gadget record type to AutoTable onClick prop callback arguments
- Replaced the `any` with the same type that is used elsewhere within the `useTable` hook
> Added proper Gadget record type to AutoTable onClick prop callback arguments

- packages/react/.changeset/rude-onions-compete.md
- packages/react/src/auto/mui/test-index.ts
- packages/react/src/auto/polaris/index.ts
- Removed `AutoTextInput` from the package export because this component is made redundant by the Gadget field specific inputs 
- The component will continue to be used internally
> Removed `AutoTextInput` from the package export because this component is made redundant by the Gadget field specific inputs 

- packages/react/src/useTable.tsx
- The removed props can come from the findMany, but are not relevant to the usage of `useTable`
- The `initialCursor` property is preferred for controlling `useTable`
> Omitted erroneous pagination options from useTable type

- packages/react/.changeset/plenty-clouds-pretend.md
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- UPDATE
- AutoTable bulk actions with custom callbacks now de-select all records to match the behavior of Gadget bulk actions
- This was a minor oversight during the previous release where the auto-record deselection system was added for Gadget bulk actions
> Updated AutoTable bulk actions with custom callbacks to de-select all records to match the behavior of Gadget bulk actions

- packages/react/src/useGlobalAction.ts
- packages/react/src/utils.ts
- UPDATE
- Some Gadget template apps have type errors because they have `useGlobalAction` and no parameter in the callback.
- `Expected 1-2 arguments, but got 0`
- This actually works and should be allowed by the type 
This will no longer have a type error with the default code snip
> Allow `useGlobalAction` callback to take no arguments

- packages/react/.changeset/shiny-fireants-learn.md
- packages/react/src/auto/mui/inputs/LazyLoadedMUIAutoRichTextInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
- packages/react/src/auto/mui/inputs/MUIAutoRichTextInput.tsx
- packages/react/src/auto/mui/test-index.ts
- packages/react/src/auto/polaris/index.ts
- packages/react/src/auto/polaris/inputs/LazyLoadedPolarisAutoRichTextInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoRichTextInput.tsx
- packages/react/src/auto/shared/AutoRichTextInput.tsx
- packages/react/src/auto/shared/AutoRichTextInputProps.tsx
- This input type was previously not exported in the `auto` packages
- In package.json, add these dependencies
```
"@gadgetinc/react":"https://codeload.github.com/gadget-inc/js-clients/tar.gz/@gadgetinc/react-v0.17.2-gitpkg-f3d72f0d",
"@mdxeditor/editor":"3.11.5",
```
- Try this out 
```jsx
import { AutoForm, AutoRichTextInput } from "@gadgetinc/react/auto/polaris";
// Note that codeMirror won't resolve the AutoRichTextInput type because of a separate types manifest concern
<AutoForm action={api.modelA.create}>
<AutoRichTextInput field="richTextField" />
</AutoForm>
```
- Observe that things look reasonable in the app
- Remove the `@mdxeditor/editor` dependency and observe that the app now has an error. The error is not great, but it matches the existing system, 
- Observe how the …
> Export AutoRichText component

- packages/react/.changeset/lazy-mirrors-smile.md
- packages/react/src/auto/hooks/useEnumInputController.tsx
- UPDATE
- Pre-populating the search bar for enum inputs makes it such that the options are pre-filtered once you click on the input. 
- It would be better to see all available options when you clock the input
- Now, the enum input search input is always initialized as empty
> Updated AutoForm enum inputs such that their search value does not get pre-populated

- packages/react/.changeset/perfect-cheetahs-hope.md
- packages/react/src/auto/hooks/useAutoButtonController.tsx
- packages/react/src/auto/mui/MUIAutoButton.tsx
- packages/react/src/auto/polaris/PolarisAutoButton.tsx
- Updated `AutoButton` such that the loading state is dependant only on fetching the action result instead of also being dependant on fetching action metadata
- This is useful to differentiate between when the button is not ready to be clicked yet, and when the action is submitting
> Updated `AutoButton` such that the loading state is dependant only on fetching the action result

- package.json
- packages/react/.changeset/proud-cameras-push.md
- packages/react/cypress/component/auto/form/AutoFormFindByObjects.cy.tsx
- packages/react/spec/auto/form/PolarisAutoFormFindByUniqueField.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/AutoFormActionValidators.ts
- packages/react/src/auto/hooks/useBelongsToInputController.tsx
- packages/react/src/auto/hooks/useRelatedModelOptions.tsx
- packages/react/src/use-action-form/utils.ts
- packages/react/src/useActionForm.ts
- pnpm-lock.yaml
- **UPDATE**
- Previously, when the `AutoForm` findBy prop was an object representing a unique field, form submissions were broken and relationship fields did not properly load related model data
- The form submission was broken because we had included the whole object as the id value on submission. This became a type error that could not be shown without advanced `react-hook-form` techniques
- The relationship fields were broken because we did not have a system for translating those object values into IDs for the model containing the action. The only way to know this is through a lookup, and a hook has been added to do so
- NOW, the findBy property should work as expected when using objects like `{uniqueFieldApiId: "uniqueValue"}`
- **TESTING**
- I've added a namespace with inter-related …
> Fixed the `findBy` object parameter for the `AutoForm` component such that related records are correctly shown and forms can be properly submitted

- packages/react/.changeset/slow-pets-give.md
- packages/react/src/auto/mui/inputs/MUIAutoDateTimePicker.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
- **UPDATE**
- Previously, the required field `*` error did not appear for dateTime fields and the error message for having a missing value was not shown 
- Now, the `*` indicator appears when the date field is required and the input properly shows the error message when caught by the frontend required field validator
> Added required indicator and required error message to date fields in AutoForm

- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/utils.ts
When working on nested forms using `useActionForm` I found that if we set the `id = nuil` on a belongs to relationship we don't call the api correctly to unlink the model
This PR resolves that
> useActionForm supports unlinking a belongsTo

- packages/react/src/auto/hooks/useTableBulkActions.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- Update
- `actionType: "delete"` bulk actions used in AutoTable will now appear as red-text buttons to differentiate their destructive nature
- Unfortunately, the controllability of the buttons in Polaris seems to be limited to that `destructive` bool value
> Make delete typed bulkActions appear red in AutoTable

- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/InternalModelManager.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/types.ts
- packages/react/spec/useEnqueue.spec.tsx
As reported in Discord several times now, people write things to fit the types, but then when trying something out will get an error from the GraphQL API:
> [GraphQL] Variable "$backgroundOptions" got invalid value "high" at "backgroundOptions.priority"; Value "high" does not exist in "BackgroundActionPriority" enum. Did you mean the enum value "HIGH"?"
We have two options here:
1. Keep the type the same, and call `toUpperCase` to ensure we send the correct value.
2. Change the type to match the GraphQL value.
(1) is nice, because it avoids any breaking changes in the types, but I got some feedback in Discord that people would be down for (2). Specifically, the following was said:
> Easy to change and is made to cope with an initial error, so it makes sense to remove it
The thing I like …
> Fix incorrect types for background options priority

- packages/react/spec/auto/inputs/PolarisAutoHiddenInput.spec.tsx
- packages/react/spec/auto/support/helper.ts
- packages/react/src/auto/hooks/useHiddenInput.tsx
This fixes using hidden inputs against belongs tos. Previously, the hidden input would set the string ID right into the form values as the value at the field, which doesn't match what `useActionForm` is expecting or what the belongs to controller already does. For belongstos, we need to suffix the path with a `.id` to have useActionForm process the form properly. Without this, the validator complains that the field value is not an object -- it's expecting it to be a `{_link: "123"}` sort of deal. We overcome this by setting the id.
This makes me think there may be other transformations we need to do within AutoHiddenInput -- are yall aware of any others?
> Fix setting belongsTo fields with AutoHiddenInput

- packages/react/.changeset/dull-walls-exist.md
- packages/react/src/auto/hooks/useBelongsToInputController.tsx
- **UPDATE**
- Previously, re-rendering an AutoForm with a findBy containing a belongsTo input would sometimes not show the related model record, despite the fact that there is a related record
- The race condition
- `useActionForm` will replace all fields in the formState with a retrieved record value. 
- This fetch DOES NOT includes relationship field values by default. This sets relationship field values to null in the form state
- `AutoForm` relationship hooks set the formState field values after doing a fetch for the related model record
- Sometimes the `useActionForm` fetch finishes after the relationship hook fetch which overwrites the relationship hook. 
- Fixed by adding the `formState.defaultValues` to the dependency array in `useBelongsToInputController`
- This way, if the …
> Fixed bug with `AutoForm` belongsTo field inputs occasionally not showing their related record upon component re-render

- packages/react/.changeset/slow-pets-give.md
- packages/react/src/auto/polaris/inputs/PolarisAutoJSONInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToInput.tsx
- See title. These 2 were simply forgotten on the first sweep
> Add required field indicators to JSON and belongsTo fields

- packages/react/.changeset/lazy-pans-push.md
- packages/react/cypress/component/auto/form/PolarisAutoHasManyInput.cy.tsx
- packages/react/src/auto/hooks/useRelatedModelOptions.tsx
- Update
- See title
- This was a consequence of our test environments not being configured with framework version 1.3 and the corresponding changes to related model filtering
> Fixed bug with loading selected related model records in AutoForm HasMany inputs in framework version 1.3

- packages/react/.changeset/big-impalas-think.md
- packages/react/src/metadata.tsx
- UPDATE
- Framework version 1.0.0 apps have empty object prototypes for the model manager which makes it impossible to determine the action API id in the same way that we do in FWVersion >=1.1
- Added a `parse the operationName to get actionApiId` system as a fallback in the event that we fail to get the action API id from the model manager
- TESTING
- Make a v1.0.0 app with this dependency. Observe that AutoForm works as expected 
- `"@gadgetinc/react": "https://codeload.github.com/gadget-inc/js-clients/tar.gz/@gadgetinc/react-v0.18.1-gitpkg-58f5b08a"`
> Fixed bug with AutoForm where the action api identifiers could not be properly determined in Gadget framework version 1.0.0

- packages/api-client-core/spec/Select-type.spec.ts
- packages/api-client-core/spec/TestSchema.ts
- packages/api-client-core/spec/default-selection.spec.ts
- packages/api-client-core/spec/helpers.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/spec/operationRunners.spec.ts
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/api-client-core/src/types.ts
This is the counterpart to https://github.com/gadget-inc/gadget/pull/13298
It adds operation builder and runner for computed view as well as generic ComputeView function types and interfaces with metadata. It introduces two variants "with variables" and "without variables" to keep things simpler. The types probably could be merged, but I had enough trouble sorting the types out as is, we can try in a follow up.
Chunk of the work was debugging and tweaking the various utility types to allow TS to infer types correctly. It was a crazy learning curve for me, it's quite possible that I still got some things wrong here. I introduced second versions of the utility types as some of the tweaks broke the dependent packages that use the original ones (react). Not all tweaks are likely necessary for …
> computed view endpoint for api client (GGT-7201)

- packages/api-client-core/package.json
- packages/api-client-core/src/graphql-live-query-utils/createApplyLiveQueryPatch.ts
See https://github.com/gadget-inc/js-clients/pull/697 for details. 
This PR just merges the api-client-core portion of the PR as it seems like you can't bump api-client-core and it's usage in a single PR. This is because the vite test does an `pnpm install` with the new version number, however that can't be found because it hasn't been released yet (until the PR is merged).
> api-client-core should propagate error for live queries

- packages/react/spec/useActionFormController.spec.tsx
- packages/react/src/use-action-form/types.ts
Shopify Polaris, in its infinite wisdom, accepts only `string | undefined` for the `value` prop on its `<TextInput/>` component. `<input/>` in the DOM accepts `string | readonly string[] | number | undefined;`, which you'd think Polaris would be ok with, but alas no. At runtime, it's absolutely fine to pass `null` to the TextInput, it works fine, it's just the type that is not ok with it. Because Gadget's API responds with `null`, not `undefined` for fields that haven't been set yet, it means that the form values type have `string | null | undefined` in them, which causes a type error by default when wiring up to a Polaris `<TextInput/>` with a `<Controller/>`.
Because so many of our users use Polaris, we think we should adjust our default types to work correctly with Polaris inputs. …
> Strip nulls from the form state type for maximum polaris compatability

- packages/react/.changeset/eleven-carrots-press.md
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
UPDATE
- Added `searchValue` prop to `AutoTable` to control the search value of the table from outside of the component itself
- This prop is compatible with `searchable:true` in AutoTable. In this case, the new `searchValue` prop will only be used to power the search when the user does not manually add their own search
> Added `searchValue` property to `AutoTable` component to control the table's search value

- packages/react-bigcommerce/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- packages/react/spec/useAction.spec.tsx
- packages/react/src/useAction.ts
- packages/shopify-extensions/package.json
The response from an upsert action was not being properly handled by `useAction` and therefore the data was not being returned to the user. This was because the `action.hasReturnType` looks like:
```
{
"... on CreatePostResult": { hasReturnType: false },
"... on UpdatePostResult": { hasReturnType: true },
}
```
in the useAction processResult it would just check if `action.hasReturnType` is truthy and if so use `mutationData.result`. However in this case the value is truthy but an object not a boolean value. 
We already have the utility inside the `api-client-core` to process the action results (which is used both by the core action runner and background actions) which handles this case correctly so this updates the code to use that instead.
> Update js-clients to process action responses

- packages/react-bigcommerce/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- packages/shopify-extensions/package.json
I forgot to release a new version of react package with the code changes. This bumps the version number.
> Bump react package version

- packages/react/.changeset/sixty-flowers-burn.md
- packages/react/src/auto/polaris/inputs/PolarisAutoEnumInput.tsx
- Updated `AutoEnumInput` props type to no longer include `allowMultiple` as it could not override the configuration of the corresponding Gadget field
- This prop was included by the Polaris Combobox props spread, and gave users the wrong idea about what could be configured in the input
> Removed `allowMultiple` from `AutoEnumInput` props type

- package.json
- packages/react/cypress/component/auto/form/PolarisAutoBelongsToInput.cy.tsx
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships-that-are-reordered_1591436327/recording.har
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/utils.ts
- pnpm-lock.yaml
we had a nasty issue with how we determined which ids have been updated/created/deleted when there are grandchildren. The ids for each array element were being addressed by the array index which the form can change (by reordering the children or deleting and appending)
This PR fixes that by addressing the existing ids not by array index but by the id of the array element
> Fix double delete on use action form

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/spec/auto/support/widgetModel.ts
- packages/react/spec/useActionFormRichFields.spec.tsx
- packages/react/src/auto/shared/AutoRichTextInput.tsx
- **UPDATE**
- `AutoRichTextInput` imported the `mdxEditor` dependency through an asynchronous function in a useEffect, and the components was stuck in a loading state until the import was resolved
- This "lazy loaded" component was then used in `LazyLoadedPolarisAutoRichTextInput.tsx`. We were effectively doing a double lazy load when we only needed to do it once
- `LazyLoadedPolarisAutoRichTextInput.tsx` was a later addition after the original `AutoRichTextInput` component was added. When I added that, I think I neglected to remove the useEffect based import, which was originally used to prevent errors when using AutoComponents without `mdxEditor`
- Now the `mdxEditor` import is directly eager loaded into the `AutoRichTextInput` component. 
- We will now rely only on the frontend …
> Updated AutoRichTextInput to eager-load dependencies instead of in a useEffect

- packages/react/spec/auto/PolarisAutoForm.spec.tsx
- packages/react/spec/auto/support/widgetModel.ts
- packages/react/spec/useActionFormRichFields.spec.tsx
- packages/react/src/auto/shared/AutoRichTextInput.tsx
(cherry picked from commit 45ef06643b6808337b5120dd471f3158f337cefe)
Originally from https://github.com/gadget-inc/js-clients/pull/713
> Updated AutoRichTextInput to eager-load dependencies instead of in a useEffect (for related-model-autoform)

- packages/react/spec/auto/MockForm.tsx
- packages/react/src/auto/AutoFormContext.ts
- packages/react/src/auto/hooks/useResultBannerController.tsx
- packages/react/src/auto/mui/submit/MUIAutoSubmit.tsx
- packages/react/src/auto/polaris/submit/PolarisAutoSubmit.tsx
- **UPDATE**
- `AutoFormMetadataContext.submitResult` used to be potentially undefined in the type, but it was always defined in practice
- Now the type is always defined so that less null checks are necessary in code, increasing readability 😄
> Make `submitResult` in `AutoFormMetadataContext` type always defined

- packages/react/spec/auto/MockForm.tsx
- packages/react/src/auto/AutoFormContext.ts
- packages/react/src/auto/hooks/useResultBannerController.tsx
- packages/react/src/auto/mui/submit/MUIAutoSubmit.tsx
- packages/react/src/auto/polaris/submit/PolarisAutoSubmit.tsx
Cherry picked commit from  https://github.com/gadget-inc/js-clients/pull/715/files
> Make `submitResult` in `AutoFormMetadataContext` type always defined (related-model-autoform)

- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships-that-are-reordered_1591436327/recording.har
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/use-action-form/utils.ts
Previously, if the edge ID value had more than one digit, it triggered a bug that prevented the edge item from being deleted. 
When we generate a map that maps the default values and their related paths, we set the new path by using the string of the current path - 2 characters. Therefore, if the ID has more than one digit, the new path becomes `foo.bar.`, which causes the transform to fail to determine whether it should update or delete its value.
This PR fixes the issue by doing the `string.split(".")` and skipping the last value in the array to remove the ID.
> Fix unable to delete values in hasMany field in useActionForm

- packages/api-client-core/src/GadgetConnection.ts
- packages/react/spec/liveQueries.spec.tsx
This prevents our urql client from re-executing live queries.
This change is to prevent the following scenario:
1. component uses `useFindMany` with `live: true`
2. component executes a mutation that touches the `__typename` the `useFindMany` references
3. cache exchange re-executes the `useFindMany` because the mutation invalidated its cache
Step 3 doesn't stop the existing live query, causing live queries to leak on the client and cause the server to keep track and push changes to live queries that aren't being used.
My [first attempt](https://github.com/gadget-inc/js-clients/pull/720) at fixing this issue was to prevent the cache exchange from re-executing live queries, however we realized this issue could happen again if something else decided to start re-executing live queries, so we …
> Don't reexecute live queries

- packages/api-client-core/package.json
Includes the live query fix in #723
> Bump api-client-core to 0.15.38

- packages/react/spec/auto/polaris/PolarisAutoForm.stories.jsx
- packages/react/src/auto/hooks/useFieldMetadata.tsx
- packages/react/src/use-table/helpers.tsx
- **UPDATE**
- Previously, custom model action params would break AutoForm
- The inputs could not be rendered because their path in the form state is simply the field name, but the `useFieldMetadata` hook would try to find an input with the path `modelName.customParamName`
- The submission would cause a GQL API error because we would include the custom field in the response query, and it would not be in the model schema because it is not a field
> Fix custom action params in AutoForm

- packages/react/cypress/component/auto/form/AutoFormInputLabels.cy.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoEncryptedStringInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoPasswordInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoTextInput.tsx
Integrating Shadcn AutoInputs for Encrypted Texts e.g Password Inputs
> Shadcn Encrypted Auto Text Inputs

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/cypress/component/auto/form/AutoPasswordInput.cy.tsx
- packages/react/cypress/component/auto/form/PolarisAutoDateTimePicker.cy.tsx
- packages/react/cypress/support/component.tsx
- packages/react/src/auto/AutoForm.ts
PolarisAutoDateTimePicker.cy.tsx was quite flakey due to async access to the default record from the metadata and this only happened when running the whole test file, and never when running the test in isolation.
Added longer timeouts for checking for the submit result banner
> extended timeouts and added test specific retries to reduce flake impact

- package.json
- packages/react/cypress/component/auto/form/AutoFormUpsertAction.cy.tsx
- packages/react/cypress/component/auto/form/PolarisAutoJSONInput.cy.tsx
- packages/react/spec/auto/MockForm.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/AutoFormContext.tsx
- packages/react/src/auto/AutoInput.tsx
- packages/react/src/auto/hooks/useJSONInputController.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
- packages/react/src/internal/gql/graphql.ts
- pnpm-lock.yaml
- https://github.com/gadget-inc/js-clients/pull/729 -> introduced a small regression where a quick flash would happen when the form would render, but all of the inputs were null since they had not been registered in the form context.
- As the fields were getting registered, they would contribute to a selection change that would control the `findby` lookup. During this lookup, the form would go back to the skeleton until the values were loaded, causing this flash
- Previously  (slo mo)
- ![CleanShot 2025-01-23 at 21 07 28](https://github.com/user-attachments/assets/70bb6baf-2175-41d5-af0e-dcedcf12df96)
- Now (slo mo)
- ![CleanShot 2025-01-23 at 21 08 17](https://github.com/user-attachments/assets/aa0487d7-9266-4ada-aa22-be7a0ff37435)
> Fix initial form flash for autoform with findby

- packages/react/src/auto/polaris/inputs/PolarisAutoFileInput.tsx
- **UPDATE**
- When file fields appeared in Polaris `AutoForm` components, the input labels did not appear correctly. 
- The input label is defined in these cases, but the polaris `DropZone` component does not seem to reliably render the label. 
- The fix is to simply render the label separate from the `DropZone` component
> Fixed default field label for `PolarisAutoInput` with `File` fields

- packages/react/src/auto/AutoInput.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneForm.tsx
- **UPDATE**
- Previously, the `selectPaths` prop was appearing in the types for ALL AutoInputs, but it is only relevant to `AutoRelationshipForm` wrapper components 
- Now, `autoInput` and `autoRelationshipForm` are separate, and `selectPaths` only appears on the relationship form wrapper props type
> Separated `autoInput` and new `autoRelationshipForm` to prevent contribution of `selectPaths` to all input props

- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneInput.tsx
The `label` prop did nothing in this component because it was never referenced. Updated such that it will take precedence over the default `metadata.name` value
> Fix `label` prop on `PolarisAutoHasOneInput`

- packages/react/src/auto/hooks/useRelatedModel.tsx
- packages/react/src/auto/polaris/inputs/relationships/RelatedModelOptions.tsx
- packages/react/src/useDebouncedSearch.tsx
- **UPDATE**
- Previously, we were using the search value directly in the related model record lookup in auto form relationship inputs
- Now, that search value is debounced to prevent excessing API calls
- The loading state of the search has also been updated to be true when the search value is in the process of debouncing
> Added debouncing to AutoForm related model record searching

- package.json
- packages/react/spec/auto/polaris/form/PolarisAutoRelationshipForm.stories.jsx
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/auto/AutoInput.tsx
- packages/react/src/auto/hooks/useAutoRelationship.tsx
- packages/react/src/auto/hooks/useFieldMetadata.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasOneForm.tsx
- packages/react/src/internal/gql/graphql.ts
- packages/react/src/useHasOneForm.ts
- pnpm-lock.yaml
- **UPDATE**
- `autoRelationshipForm` wrapper previously registered `selectPaths` incorrectly by prepending the current field API id in front of the selected field instead of prepending the whole path of the current field. 
- This would make nested relationship forms unable to show the selected paths in labels without having them as AutoInputs or updating the select 
- Nesting `AutoHasOneForm` and `AutoBelongsToForms` inside of an `AutoHasManyForm` would cause throw an exception when used
- This is because those forms included indexes from their parent `HasManyForm` into the paths used for their own relationship form context
- Eg. Their paths were `parent.children.0.grandchildren.0....` instead of `parent.children.grandchildren...`
- Fixed by updating the context to use the metadata path, …
> Updated AutoFormRelationshipForms to use metadataPath instead form state path

- packages/react/cypress/component/auto/form/ShadcnAutoBelongsToInput.cy.tsx
- packages/react/cypress/support/PolarisAdapter.ts
- packages/react/cypress/support/auto.tsx
- packages/react/spec/auto/shadcn-defaults/ShadcnAutoForm.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnAutoEnumInput.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnAutoJSONInput.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnFileInput.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/form/ShadcnAutoRelationshipForm.stories.jsx
- packages/react/spec/auto/storybook/table/SelectableDesignSystemAutoTableStory.tsx
- packages/react/src/auto/polaris/index.ts
- packages/react/src/auto/shadcn/index.ts
- packages/react/src/auto/shadcn/unreleasedIndex.ts
- A new react version needs to be released in order to upgrade the api-client-core version.
- This PR removes the indexes for the new and unreleased AutoCompoent changes
> Remove unreleased AutoComponents updates from index files

- packages/react/spec/auto/shadcn-defaults/ShadcnAutoForm.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnAutoEnumInput.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnAutoJSONInput.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnFileInput.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/form/ShadcnAutoRelationshipForm.stories.jsx
I had to rename the import file to safely release the next version of the react package. Unfortunately the `auto update imports` functionality does not use the correct file extensions to work with storybook. Fixed quick 🫡
> fix shadcn storybook imports

- packages/react-bigcommerce/package.json
- packages/react-shopify-app-bridge/package.json
- packages/react/package.json
- packages/shopify-extensions/package.json
Bumps react versions to include api client core with revert
> Bump versions for react and api client core

- packages/react/spec/auto/shadcn-defaults/inputs/form/ShadcnAutoRelationshipForm.stories.jsx
- packages/react/src/auto/hooks/useRequiredChildComponentsValidator.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyForm.tsx
- packages/react/src/useBelongsToForm.ts
- packages/react/src/useHasOneForm.ts
- UPDATE
- Many of the relationship form components did not make sense when they have not input fields. 
- belongsTo - Without children, the modal is empty to create/update
- hasOne - Without children, the modal is empty to create/update
- hasMany - Without children, the expanded child records are empty
- hasManyThrough- Makes sense without children
- In this case,  child elements are be based on the join model. The join model does not need to have fields beyond the 2 linking belongsTo fields to make sense
- Now, there is a big validation error when children are not included in the `AutpoRelationshipForm` component
- In the future, it may be nice to automatically show all fields in the related model if there are no children. This behaviour will match the AutoForm wrapper. but this is an …
> Add validation to belongsTo/hasOne/hasMany AutoRelationshipForms to ensure that they have valid react children

- packages/react/cypress/support/auto.tsx
- packages/react/spec/auto/shadcn-defaults/components/Form.tsx
- packages/react/spec/auto/shadcn-defaults/index.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
- packages/react/src/auto/shadcn/elements.tsx
- **Fix need for a bunch of custom casting with explicitly always included findBy type**
- **Don't use shadcn form -- it overrides react-hook-form context that we need**
- **Make the shadcn form layout a bit nicer**
> shadcn fixes 2

- packages/react/cypress/component/auto/form/AutoHasOneForm.cy.tsx
- packages/react/spec/auto/polaris/form/PolarisAutoRelationshipForm.stories.jsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/SearchableSingleRelatedModelRecordSelector.tsx
- packages/react/src/auto/shadcn/inputs/relationships/SearchableSingleRelatedModelRecordSelector.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoBelongsToForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasOneForm.tsx
- packages/react/src/use-action-form/utils.ts
- packages/react/src/useBelongsToForm.ts
- packages/react/src/useHasOneForm.ts
- packages/react/src/useSingleRelatedRecordRelationshipForm.ts
- UPDATES
- removed `renderSelectedRecord`. This is redundant with the primary/secondary/ternary record label system 
- `useSingleRelatedRecordRelationshipForm` 
- There was a lot of overlap between the form hooks for belongsTo and hasOne. I've consolidated their shared logic into this one hook and added extensions where needed
- Ex - HasOne has more complicated logic for creating a new record
- `SearchableSingleRelatedModelRecordSelector`
- In Polaris and Shadcn, we had an effectively identical component that was used to search and select for records on the related model. It has now been consolidated into a single component in both Polaris and Shadcn 
- `hasOne` - GQL argument shaping
- Previously, the inclusion of `_unlink` would ignore all of the other params in the form state. This …
> AutoHasOneForm - UI overhaul, allow selected record replacement, consolidate shared functions with BelongsTo

- packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoDateTimePicker.tsx
- packages/react/src/useDateTimeField.ts
Fix issue where null dates in both Shadcn and Polaris were defaulting to 1970 .
> Explicitly handle null values for Polaris and Shadcn AutoDatePickers

- packages/react/cypress/component/auto/form/AutoHasManyThroughForm.cy.tsx
- packages/react/spec/auto/polaris/form/PolarisAutoRelationshipForm.stories.jsx
- packages/react/spec/useActionFormNested.spec.tsx
- packages/react/src/auto/AutoInput.tsx
- packages/react/src/auto/hooks/useAutoRelationship.tsx
- packages/react/src/auto/hooks/useFieldMetadata.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasManyThroughForm.tsx
- packages/react/src/use-action-form/utils.ts
- packages/react/src/useHasManyThroughForm.ts
- packages/react/src/utils.ts
- UPDATE
- It was previously impossible to edit the sibling record from within a AutoHasManyThroughForm as the variable passed to the `joinModel-belongsTo-relatedModel` field would always be `_link` instead of a nested action
- now, that join model belongs to field gets a nested action formed if it is called in the context of a AutoHasManyThroughForm.
> Allow sibling edit in AutoHasManyThroughForm

- packages/react/.changeset/khaki-keys-beg.md
- packages/react/spec/auto/shadcn-defaults/inputs/ShadcnFileInput.stories.jsx
- packages/react/src/auto/hooks/useBelongsToController.tsx
- packages/react/src/auto/hooks/useBooleanInputController.tsx
- packages/react/src/auto/hooks/useDateTimeField.ts
- packages/react/src/auto/hooks/useEnumInputController.tsx
- packages/react/src/auto/hooks/useFileInputController.tsx
- packages/react/src/auto/hooks/useHasManyController.tsx
- packages/react/src/auto/hooks/useHasManyThroughController.tsx
- packages/react/src/auto/hooks/useHasOneController.tsx
- packages/react/src/auto/hooks/useJSONInputController.tsx
- packages/react/src/auto/hooks/usePasswordController.tsx
- packages/react/src/auto/hooks/useRoleInputController.tsx
- packages/react/src/auto/hooks/utils.ts
- packages/react/src/auto/polaris/inputs/PolarisAutoBooleanInput.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoPasswordInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoBooleanInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoDateTimePicker.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoPasswordInput.tsx
- packages/react/src/auto/shared/AutoRichTextInput.tsx
- **UPDATE**
- Previously, the only field based validation that was ran on AutoInputs was that the field existed in the metadata. There were no errors for when an existing field was put into an `AutoInput` of the wrong field type
- Now, most field type specific AutoInputs have a new validator that ensures that a field API ID string corresponding to the correct field type is given. 
- Why don't all field types have validators?
- String based inputs did not get validators because it may be the case that someone wants to use one field's UI elements for a different field type
- Eg. Someone wants to have a show/hide system for a `string` field and uses `AutoEncryptedInput`
- Many of the string based inputs use the same base `AutoTextInput` component, exported under fieldType specific names. …
> Add field type specific validations to many AutoInputs

- packages/react/spec/auto/AutoComponentsApiClientTypeChecker.tsx
- packages/react/spec/auto/polaris/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/shadcn-defaults/ShadcnAutoForm.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
- UPDATE
- Global actions caused type errors when used in `AutoForm`. This was not a problem in older versions, and I'm not certain what caused this.
- The types for `AutoForm` components have been updated to account for Global actions.
- The `AutoFormProps` type has been simplified to remove the last 2 type arguments. 
- They did not contribute anything that could not be inferred from the other type args
- They resulted in the `defaultValues` type being `Record<string, unknown>` instead of the real type from the API client
> Fix type error for global actions in AutoForm

- packages/react/src/auto/hooks/useHasManyThroughController.tsx
- UPDATE
- Previously, the dropdown for HMT fields did not respect the given `optionLabel` prop at all. 
- It simply needed to reshape the props such that the `input` controller was compatible with the `form` controller, which is responsible for making the related model options
> Fix `AutoHasManyThroughInput` usage of `optionLabel` in dropdown

- packages/react/src/auto/hooks/useRelatedModel.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisListMessages.tsx
- packages/react/src/utils.ts
- **UPDATE**
- Previously, scrolling in the related model record drop down was jumpy. It did not always feel like a smooth scroll like it did in the gizmo hasMany records drop down in storybook
- this issue was caused by the fact that the records are sorted by ID, however, they are sorted by ID as strings instead of as numbers. 
- eg. `1,10,11,12,13,14,15,16,17,18,19,   2,20,21,22.....`
- this was probably never noticed because this behaviour was generally tested in the gizmos has many field on the widget model, and all records in the gizmo model have IDs greater than 1000. This is an issue that is more appearance when the model records start at 1
- Now, the ID strings are converted to number before they are sorted. You can now observe smooth scrolling in all of the auto relationship …
> Fix jumpiness in AutoRelationshipInput related model records dropdowns when paginating

- packages/react/spec/auto/AutoComponentsApiClientTypeChecker.tsx
- packages/react/src/auto/AutoForm.ts
- Unfortunately when I first tried to tighten up the type in this PR, I did not realize that the types for relationship fields would be based on the GQL nested action types instead of JS types. 
- https://github.com/gadget-inc/js-clients/pull/780
- if you have `childModel.parentModel.name` in the defaultValues prop, you would get a type error saying `only "create", 'update', 'delete', '_link' are valid property names`. This is wrong because those would be treated like field names instead of nested actionss in useActionForm
- Reshaping the GQL nested action based type to be more like the JS type using only TS type operations is gonna be very hard. 
- Fixing this type to reflect the JS expected type is probably gonna easier to implement and maintain as an `api-client-core` change
> Loosen type of AutoForm `defaultValues` prop

- packages/react/src/auto/shared/styles/rich-text.css
The border radius no longer applies to the bottom of the toolbar.
> fix bottom border radius on AutoRichTextInput toolbar

- packages/react/cypress/component/auto/form/AutoForm.cy.tsx
- packages/react/cypress/component/auto/form/AutoFormDateTimePicker.cy.tsx
- packages/react/src/auto/AutoForm.ts
- UPDATE
- Cypress tests would never fail if they were defined in async functions. Terrifying degree of false positives 💀 
- One of the now sync test exposed an issue with the field registration system where we would still run validations if there were no registered autoInputs.
> Prevent AutoForm validations when there are no registered autoInput children

- packages/react/.changeset/seven-bikes-refuse.md
- packages/react/cypress/component/auto/form/PolarisAutoHasManyInput.cy.tsx
- packages/react/spec/auto/polaris/PolarisAutoForm.stories.jsx
- packages/react/spec/auto/shadcn-defaults/ShadcnAutoForm.stories.jsx
- packages/react/src/auto/hooks/useBelongsToController.tsx
- packages/react/src/auto/hooks/useHasManyController.tsx
- packages/react/src/auto/hooks/useHasManyThroughController.tsx
- packages/react/src/auto/hooks/useHasOneController.tsx
- packages/react/src/auto/hooks/useRelatedModel.tsx
- packages/react/src/auto/interfaces/AutoRelationshipInputProps.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyForm.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasManyForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasOneForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnListMessages.tsx
- **UPDATE**
- Added `recordFilter` prop
- All relationship inputs receive this since they all get a related model record dropdown
- belongsTo and hasManyThrough relationship forms get this since they have dropdown for existing record selection 
- hasOne and hasMany relationship forms do NOT get this since they do not currently support existing record selection 
- It is omitted from their input type 
- Manually audited that the `recordFilter` prop works properly for all of the components that it is available on
> Added new `recordFilter` prop to allow the related model options in the dropdown to be filtered

- packages/react/spec/auto/polaris/form/PolarisAutoFormErrors.stories.jsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/AutoFormContext.tsx
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
Nesting an autoForm within another AutoForm causes the submission to break completely. This should be an error case in the first place
> Add error for nesting AutoForm inside another AutoForm

- packages/react/src/auto/hooks/useRelatedModel.tsx
- packages/react/src/auto/interfaces/AutoRelationshipInputProps.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasManyThroughForm.tsx
- packages/react/src/useHasManyThroughForm.ts
in `AutoHasManyThrough`, not having any react children did not impede the usage of the component, but this was a top error. Now, this is no longer a type error
> Make `children` optional in `AutoHasManyThrough` form

- packages/react/src/useHasManyThroughForm.ts
- UPDATE
- Previously in AutoHasManyThroughForm, if you have a join record that does not point to an existing sibling model record, you would get a frontend breaking error
- Deleting a sibling model record would break the base model HMT-form
- Model data breaking the frontend is really bad 😢 
- Now, joinModel records are only considered in the HMT-form if they properly point to an existing sibling record
> Ignore join records that do not point to a sibling record in AutoHasManyThroughFrom

- packages/api-client-core/src/InternalModelManager.ts
A user on discord invoked `api.thing.internal.deleteMany(["1", "2", "3"])` which is wrong -- the function accepts an options object with a filter and a sort, but the type had those properties marked as optional, which meant that the array actually passed the typecheck! The right invocation is `api.thing.internal.deleteMany({filter: { ...}})`. Since this is a really sensitive operation, I think we should be more annoying about the required inputs so that users are forced to pass a filter of some sort. They can still delete everything by doing `api.thing.internal.deleteMany({filter: {}})`, but I think we should make that done explicitly instead of by accident if you don't pass the right options.
This is a breaking types change which I am ok to just YOLO -- functionality is unaffected but I …
> Strengthen internal .deleteMany type to require being passed a filter

- packages/react/.changeset/rotten-news-rule.md
- packages/react/cypress/component/auto/form/AutoHasManyThroughForm.cy.tsx
- packages/react/spec/auto/polaris/form/PolarisAutoRelationshipForm.stories.jsx
- packages/react/spec/auto/shadcn-defaults/inputs/form/ShadcnAutoRelationshipForm.stories.jsx
- packages/react/src/auto/hooks/useFieldMetadata.tsx
- packages/react/src/auto/hooks/useHasManyThroughController.tsx
- packages/react/src/auto/polaris/index.ts
- UPDATES
- Banning Relationships in HMT forms
- The resulting GQL request is completely incorrect when relationship fields are used within `AutoHasManyThrough` forms. 
- It seems that the form state does not get updated properly for relationships.
- This is a problem on both the join model relationships and sibling model relationships
- For now, an error will prevent users from thinking that this is supported. In the future, it is feasible to add support for this smoothly without breaking change
- No changes for non-relationship fields being used in a `AutoHasManyThroughForm`. Access to sibling and join model fields is still good
- New HMT form join record input system
- previously, we relied on having `field="joinModelName.joinModelField"` inside of AutoInputs inside of HMT form …
> Error for relationship fields in `AutoHasManyThrough` form + New join model AutoInput system

- packages/api-client-core/package.json
- packages/api-client-core/spec/mockActions.ts
- packages/api-client-core/spec/operationBuilders.spec.ts
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/operationBuilders.ts
- packages/api-client-core/src/operationRunners.ts
- packages/react/src/useEnqueue.ts
Right now this code breaks in a gadget app:
```
const handles = await api.enqueue(api.todo.bulkUpsert, input)
return await Promise.all(handles.map((handle) => handle.result()))
```
This is because we are not correctly building the graphql query in cases where the `hasReturnType` between an action and its bulkAction are different.
This PR changes this so that if a bulkAction has a reference to its `singleAction` we will use that to generate the query for background action results; things will continue to work for existing clients and non-upsert actions
> Background action upsert responses

- packages/react/src/auto/hooks/useFileInputController.tsx
- packages/react/src/auto/polaris/inputs/PolarisAutoFileInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoFileInput.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoInput.tsx
- **UPDATE**
- ShadcnAutoFileInput 
- Some shared behaviour with Polaris AutoFilInput has been refactored to the shared controller
- Removed bad `accepts` label when there are no file type validations 
- Added a placeholder file icon for non image files
> Update shadcn auto file input

- packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
Previously this was only exported on the Polaris side. Updated to also be exported on the Shadcn side
> add `AutoHasManyThroughJoinModelForm` to shadcn export

- packages/react/src/auto/polaris/PolarisAutoTable.tsx
Previously there was no placeholder and the borderless searcher was hard to see when blurred. Now, a simple `Search` placeholder value is added
> add search  placeholder to Polaris AutoForm

- packages/react/cypress/component/auto/form/AutoFormDateTimePicker.cy.tsx
- packages/react/spec/auto/shadcn-defaults/components/Calendar.tsx
- packages/react/src/auto/hooks/useDateTimeField.ts
- packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoDateTimePicker.tsx
- packages/react/src/auto/shadcn/inputs/auto-date-time-input.css
- packages/react/src/dateTimeUtils.ts
- **UPDATE**
- Changed the default `Calendar` component file to be based on the more recent version of `react-day-picker`. 
- Shadcn uses an outdated version of this component in their docs and this is called out by the `react-day-picker` docs that they point out. The version provided by the Shadcn docs did not have year selection, and it also had a lot of style issues that would need a lot of advanced styling out of the box to look reasonable. 
- https://date-picker.luca-felix.com/
- Made the state of the date and time pickers completely dependent on the form state
- There were previously some `useStates` that were used to track the time and date independently of the form state. Those had the possibility of getting out of sync
- Replaced the previous `input with time validation` approach …
> Reworked Shadcn AutoComponents DateTime picker

- packages/react/cypress/component/auto/form/AutoFormDateTimePicker.cy.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoDateTimePicker.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoTimeInput.tsx
- Update
- `import "./something.css"` does not play nice with SSR in Gadget apps. 
- This was affecting the DateTime picker because of the required css file to make the `input type="time"` dropdown not appear
- The part that requires css has now been moved to a new file that will be lazy loaded. This was inspired from the `AutoRichTextInput`  system of getting in the custom css file
> make shadcn dateTime picker use Lazyload to avoid SSR issues with css files

- packages/api-client-core/src/GadgetConnection.ts
Without the `keepAlive` option the websocket used for live queries does not send out ping messages. This is a problem as after the initial connection and subscription messages no more messages are sent to the server. This means that the connection could no longer be active without realising it.
Following the example in:
[ttps://github.com/enisdenjo/graphql-ws/blob/5161bd91388677893badb8dbaca5c6587095199b/src/client.ts#L266-L303](https://github.com/enisdenjo/graphql-ws/blob/5161bd91388677893badb8dbaca5c6587095199b/src/client.ts#L266-L303)
I have set the `keepAlive` parameter with a 5 second interval and waiting at most 2 seconds to get a response from the server. This is slightly lower than the example which uses 10 second intervals, and a 5 second timeout as I expect live queries to be …
> Add a ping to live queries to ensure socket is active

- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
- Updated shadcn autoTable to respect `selectable=false`
> Properly disable shad table row selection when `selectable=false`

- packages/react/src/auto/polaris/PolarisAutoTable.tsx
This `F` keyboard shortcut applies to the whole page and would hijack focus, even in other textboxes. I've simply removed this keyboard shortcut as always clicking to search seems a lot less bad than focus highjacking
> Remove PolarisAutoTable `F` keyboard shortcut

- packages/react/cypress/support/auto.tsx
- packages/react/src/auto/index.tsx
- packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
- packages/react/src/auto/shadcn/ShadcnDefaultPreventedButton.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoDateTimePicker.tsx
- packages/react/src/auto/shadcn/inputs/relationships/SelectedRelatedRecordTags.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoBelongsToForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoBelongsToInput.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasManyForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasManyThroughForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasOneForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasOneInput.tsx
- packages/react/src/auto/shadcn/submit/ShadcnAutoSubmit.tsx
- packages/react/src/auto/shadcn/table/ShadcnAutoTableBulkActionSelector.tsx
- UPDATE
- Normally, you'd never want to submit a form unless you're explicitly hitting a submit button, and it'd be quite painful to manually add a default prevention system to every single button.
- Now, instead of using the given button directly. we use a button with a modified onClick that prevents the default behaviour of submitting 👍
> Prevent default in Shadcn button in AutoForms

- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
- Update
- The column sort icons were appearing over the checkbox. The fix was to simply change where the z-index was applied
> fix minor z-index issue with autoTable select all chceckbox

- packages/react/src/auto/shadcn/ShadcnAutoButton.tsx
- packages/react/src/auto/shadcn/unreleasedIndex.ts
- UPDATE
- Previously, the types for many AutoComponents was not included in the `index` file, which made it a type error to re-export those imported components
- ex > `export {makeAutoComponents} from '@gadgetinc/react/auto/shadcn'; ` would have a TS error when imported in other local files in a project 
- The fix is to simply include all of the types explicitly in the index file.
> Export all autocomponent types explicitly in Shadcn package to prevent portability issues

- package.json
- packages/api-client-core/src/GadgetFunctions.ts
- packages/api-client-core/src/types.ts
- packages/react/spec/useView.spec.tsx
- packages/react/src/index.ts
- packages/react/src/useView.ts
- packages/react/src/utils.ts
- pnpm-lock.yaml
This adds a react `useView` hook to accompany the imperative computed view functions we're already generating in fv1.4 . `useView` works pretty similarly to a finder in that we grab the function off the api client and run half of it to get the operation plan, and then execute the actual thing using the urql hook. Computed views have no built in support for pagination so its simpler than a findMany or what have you, but they are typed so we do the ole fish-out-the-type-from-a-fake-property-on-the-function-thing.
The plan for releasing this is to stick it in the next react version but not announce support for a while yet while we dogfood and do an internal alpha methinks.
[no-changelog-required]
> Add computed view hook

- packages/react/.changeset/popular-lobsters-cheat.md
- packages/react/src/auto/AutoTable.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
- a new loading skeleton profits been added to auto table in order to allow people to override the default loading skeleton component
- this was suggested by people on discord here https://discord.com/channels/836317518595096598/1278488062158176338
> Added new `loadingSkeleton` prop to AutoTable

- packages/react/spec/auto/shadcn-defaults/components/Command.tsx
- packages/react/src/auto/shadcn/inputs/ShadcnAutoComboInput.tsx
There was a bad extra bottom border in shadcn comboboxes. Unfortunately this is not overridable in through passing in `className` to the shadcn provided component, so the base component has to be updated. I will update this on the Gadget side separately 
BEFORE
AFTER
> Remove bad extra bottom border in shadcn comboboxes

- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
This looked bad on Firefox without this added style. Now it looks better on all browsers
> Add `inline-flex` to shadcn autotable checkboxes

- packages/react/.changeset/afraid-walls-fetch.md
- packages/react/spec/auto/storybook/SelectableDesignSystemUtils.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/polaris/PolarisAutoForm.tsx
- packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
Added `loadingSkeleton` prop to AutoForm to override the default skeleton component.
> add `loadingSkeleton` prop to AutoForm to match AutoTable

- packages/react/src/auto/AutoInput.tsx
- packages/react/src/auto/hooks/useSelectedPathsFromRecordLabel.tsx
- There was a type error here because the the `AutoRelationshipInput` wrapper erroneously extended the whole type relationship form props type with `children`  included
> Fix type error in AutoHasManyThroughForm to make children optional

- package.json
- packages/react/.changeset/violet-mirrors-confess.md
- packages/react/spec/auto/storybook/form/AutoRelationshipForm.stories.tsx
- packages/react/spec/auto/storybook/form/SelectableDesignSystemAutoFormStory.tsx
- packages/react/src/auto/interfaces/AutoRelationshipInputProps.tsx
- packages/react/src/useHasManyThroughForm.ts
- pnpm-lock.yaml
- Added `allowMultipleSelections` prop to `AutoHasManyThroughForm` to control if sibling records can be linked multiple times through different join model records
- In hasManyThough, you sometimes do not want to allow for a multi link between the base model and the sibling model. 
- Ex - Student hasMany courses through registration
- Student registered multiple times in the same course is not desired 
- Ex - Buyer hasMany auctions through bid
- Buyers can bid multiple times in the same auction
> Added `allowMultipleSelections` prop to `AutoHasManyThroughForm` 

- packages/react/src/auto/shadcn/table/cells/ShadcnAutoTableTextCell.tsx
- On truncated strings, the text color was not legible on the background color. Updated to explicitly set the color
> fix ShadcnAutoTableTextCell tooltip text color

- packages/react/.changeset/fair-rabbits-lick.md
- packages/react/cypress/component/auto/form/AutoHasManyThroughForm.cy.tsx
- packages/react/spec/auto/storybook/form/AutoForm.stories.tsx
- packages/react/spec/auto/storybook/form/AutoRelationshipForm.stories.tsx
- packages/react/src/auto/AutoForm.ts
- packages/react/src/auto/AutoInput.tsx
- packages/react/src/auto/hooks/useSelectedPathsFromRecordLabel.tsx
- packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx
- packages/react/src/auto/shadcn/inputs/relationships/ShadcnAutoHasManyThroughForm.tsx
- packages/react/src/metadata.tsx
- **UPDATE**
- `AutoHasManyThroughForm` had a bug where the fields within were registered on paths that were different from their paths on the real form state
- Fetching and submitting were always pathed based on the implicit join model hasMany field
- Eg. Course hasMany students through registration - course.registrations.student.name, course.registration.startDate
- The resulting nested action was also pathed based on this `implicit join model hasMany field` system.
- The problem was that the metadata pathing was based on the actual HMT field instead of the implicit joinModelHasMany field. This mismatch of paths caused the following issues 
- The path of the yupResolver did not agree with the form state path for AutoInputs within AutoHasManyThroughForm.
- Validations were not run on …
> Fix pathing of validations on AutoHasManyThroughForm

- package.json
- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/.changeset/silent-starfishes-cough.md
- packages/react/spec/auto/shadcn-defaults/__snapshots__/shadcnClassnameSafelist.spec.ts.snap
- packages/react/spec/auto/shadcn-defaults/shadcnClassnameSafelist.spec.ts
- packages/react/spec/useView.spec.tsx
- packages/react/src/auto/shadcn/GadgetShadcnTailwindSafelist.ts
- packages/react/src/index.ts
- packages/react/src/useView.ts
- pnpm-lock.yaml
This adds support for inline views (views that are plain strings instead of .gelly files on the backed) and fixes support for named views mounted on models in the `useView` hook. See the tests!
[no-changelog-required]
> Add support for inline views and fix operation name on model namespaced views

- packages/react/CHANGELOG.md
- packages/react/src/auto/shadcn/index.ts
- packages/react/src/index.ts
See changelog entry, that version hasnt actually been released yet so sneaking this into that one
> Export autocomponent types from the root file to ensure type portability

- packages/react-shopify-app-bridge/spec/Provider.spec.tsx
- packages/react-shopify-app-bridge/src/Provider.tsx
- packages/react/.changeset/young-shoes-hear.md
> Gracefully handle errors trying to get the shop installation data with missing scopes in mock embed mode

- packages/react/src/auto/AutoForm.ts
- Allow `null` as a valid type for the `title` prop in AutoForm to prevent the title from rendering
> Allow null in AutoForm `title` prop type

- packages/api-client-core/src/GadgetFunctions.ts
- packages/react/spec/useView.spec.tsx
- packages/react/src/useView.ts
Computed view planners expect to be passed full options objects for each variable, not just the list of variable values, oops.
> Pass full variables options down to computed view variable planner functions

- packages/react/spec/auto/shadcn-defaults/__snapshots__/shadcnClassnameSafelist.spec.ts.snap
- packages/react/src/auto/shadcn/GadgetShadcnTailwindSafelist.ts
- packages/react/src/auto/shadcn/table/ShadcnAutoTableSearch.tsx
- UPDATE
- Previously, the search bar was a fixed width and would spill out of the container on slim screens
- Now, the search bar will shrink in size as the parent container shrinks
> Update shadcn AutoTable search sizing to be wider and to compress as the page compresses

- packages/react/src/auth/useSession.ts
- UPDATE
- `useSession` works on apps that do not have a session model if you do `useSession(api)`, but there is an erroneous type error. This has been fixed so that there is no longer a type error
> Updated `useSession` so that there is no type error when apps do not have `user` models

- packages/react/.changeset/gorgeous-falcons-grow.md
- packages/react/spec/auto/hooks/useTable.spec.tsx
- packages/react/spec/auto/polaris/table/PolarisAutoTable.spec.tsx
- packages/react/spec/auto/storybook/table/AutoTable.stories.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
- packages/react/src/auto/shadcn/table/ShadcnAutoTableColumnSortIndicator.tsx
- packages/react/src/use-table/helpers.tsx
- packages/react/src/use-table/types.ts
- UPDATE
- A discord user asked if they could add custom react content to the column headers in AutoTable. We did not allow this in the types to follow the Polaris precedent, but since it works, I've updated the types to allow for it 
Example - Dynamically changing color text
> Updated AutoTable to allow custom column header components

- .github/pull_request_template.md
> Changing the pr template so that it works with the changelog application

- packages/api-client-core/spec/support.spec.ts
- packages/api-client-core/src/support.ts
Small change to how we format a combined error to iterate through the GrahpQL errors and append the network error.
[no-changelog-required]
> Fixup combined error

- packages/api-client-core/spec/GadgetConnection-suite.ts
- packages/api-client-core/src/ClientOptions.ts
- packages/api-client-core/src/GadgetConnection.ts
- packages/api-client-core/src/support.ts
This PR introduces a new property in `browserSession`, `shopId`, that allows apps like Shopify theme app extensions to set up a session with a Shopify tenancy.
This allows use cases like fetching publicly accessible data for the specific shop without manually passing in the shop ID.
This PR also allows setting authentication modes at the top level, i.e. no need to declare the modes under the `authenticationMode`.
<details><summary>Click here to see an example usage</summary>
Example usage:
```liquid
<script src="https://shop-auth-mode--development.ggt.pub/api/client/web.min.js" defer="defer"></script>
<script>
document.addEventListener("DOMContentLoaded", function () {
const client = new Gadget({
browserSession: {
shopId: {{ shop.id }},
},
});
client.getCurrentShop().then((result) => { …
```
> Introduce `shopId` in `browserSession` to set shop tenant

- .github/pull_request_template.md
Reverts gadget-inc/js-clients#871
> Revert "Changing the pr template so that it works with the changelog application"

- packages/react-shopify-app-bridge/package.json
- packages/react-shopify-app-bridge/src/Provider.tsx
This fixes the provider from `@gadgetinc/react-shopify-app-bridge` to be SSR compatible so that the `useGadget` hook will use the server-side shopify install state hint to power the `isAuthenticated`property
> adds the shopify install state hint to the standalone provider

- packages/react/src/auto/shared/AutoRichTextInput.tsx
BEFORE
NOW
- **UPDATE**
- Antoine noticed that there were a lot of bugs and usability issues with the code and diff views in the AutoForm rich text input. 
- This PR removes them since they are rarely used and provide a bad experience
- Pain points
- The diff view doesn't really make sense. You can edit the old and new, and the state resets if you change to the regular view and back
- The code view is not usable. Every single keystroke blurs the input.
> Removed diff and code view from the AutoForm richText inputs

- packages/react/spec/auto/storybook/table/AutoTableActions.stories.jsx
- packages/react/src/auto/hooks/useTableBulkActions.tsx
- packages/react/src/auto/polaris/PolarisAutoTable.tsx
- packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
- packages/react/src/auto/shadcn/table/ShadcnAutoTableBulkActionSelector.tsx
- Things that were in the select were not included in the action callback
- This is because we passed the rows to the custom callbacks instead of the raw record
> Include complete raw record in AutoTable callbacks
