packages/api-client-core/src/ClientOptions.ts
packages/api-client-core/src/GadgetConnection.ts
packages/api-client-core/src/InMemoryStorage.ts
packages/api-client-core/src/index.ts

To avoid ITP preventing cookie auth from working
See https://github.com/gadget-inc/gadget/pull/1343

Switch to sending authorization information over a channel we can control

---

packages/api-client-core/src/GadgetConnection.ts

urql, the graphql react client library we use, has a light weight caching feature that reloads queries shown on screen when any mutation that might have changed the data runs. See https://formidable.com/open-source/urql/docs/basics/document-caching/ . You get it out of the box when using urql normally, but right now when using Gadget's react hooks, it is off by accident. This is because we ask users to pass in our highly-configured urql client, and we don't include the exchange. I didn't include it initially because it doesn't make much sense in a server-to-server communication context where you expect and API client to make API calls and not cache data that happened to have been fetched recently, but in the browser, urql has chosen this as default behaviour and I agree it makes sense. …

Use urql's cache exchange when running in the browser by default

---

packages/api-client-core/src/GadgetConnection.ts

As we continue to investigate the WS connection issue, here is what our understanding of the most common occurrence looks like:
- A `subscriptionClient` is created within the sandbox
- It attempts to make a connection to the API
- After 10 seconds a userland timeout within the client is triggered - this tears down the client but does not affect the ongoing request
- After 12 seconds nothing else happens - meaning NGINX's `proxy-connect-timeout` is not triggered
- After 60 seconds the request is killed, likely caused by `proxy-read-timeout` in NGINX
- Given the failure more - NGINX attempts to reconnect with another host - this request goes through
- After this successful connection, everything is dropped because the client in was torn down after the 10s mark
What we would have wanted to …

Retry WS on connection failure

---

flake.nix
packages/api-client-core/package.json
yarn.lock

Ensure we match v8 of WS.
Also upgrade Jest to match Gadget.

Upgrade ws

---

packages/api-client-core/Readme.md

Added a note so we remember to update the `UserlandDependencyVersions` variable in gadget mainline.

Added note to update UserlandDependencyVersions

---

packages/api-client-core/package.json
packages/api-client-core/src/InternalModelManager.ts

...to allow for more accurate nomenclature on doc code samples.

Update nomenclature on `findMany` internal query creation

---

packages/react/README.md

Fixes the React client example in `packages/react/README.md`

`packages/react/README.md`: Fix example

---

packages/api-client-core/package.json
packages/api-client-core/src/GadgetConnection.ts

:woman_facepalming: lodash isn't included in package.json and we probably don't want to add it.

Remove reliance on implicit lodash dependency

---

packages/react/package.json

Update `@gadgetinc/api-client-core` version to match the version that we generate for app clients

Bump @gadgetinc/api-client-core dependency version

---

packages/api-client-core/src/GadgetConnection.ts

The client's dispose function can throw, let's handle it with a `.catch` to ensure it doesn't cause and "Uncaught promise rejection".

Dispose of the client with catch

---

.github/actions/setup-test-env/action.yml
package.json
yarn.lock

Repeats fix made in https://github.com/gadget-inc/examples/pull/90

Use latest stable release of nix for CI

---

packages/api-client-core/src/GadgetConnection.ts

The retry version of: https://github.com/gadget-inc/gadget/pull/6140

Retry connection init wait close error

---

packages/react-shopify-app-bridge/package.json

Bump react-shopify-app-bridge v0.10.2

---

packages/api-client-core/package.json
packages/api-client-core/spec/GadgetRecordList.spec.ts
packages/api-client-core/spec/InternalModelManager.spec.ts
packages/api-client-core/src/InternalModelManager.ts

Reverts gadget-inc/js-clients#185

Revert "bulkCreate method in api-client-core 0.13.7"

---

packages/api-client-core/src/InternalModelManager.ts

Not exactly sure why, but before this change, the `InternalModelManager` class wrapped each of the write operations it could do in a transaction block. I don't think this really has an effect other than making them slower.
- when already inside a transaction, the `this.connection.transaction` block doesn't do anything special, it just carries on the existing outer transaction
- when not already inside a transaction, the `this.connection.transaction` block starts a graphql-ws client and sets it up and returns it. The InternalModelManager then takes it, does the one write with it, and returns, which means that user can't have ever added work into that transaction. The transaction could *only* have done the one thing inside it.
I think this is legacy thing from the very early days of this …

Don't start new, single operation transactions in the internal model manager

---

packages/api-client-core/package.json
packages/react-shopify-app-bridge/package.json
packages/react/package.json

Release new api-client-core and react versions with ESM and bugfixes

---

packages/react-shopify-app-bridge/src/Provider.tsx

I want to be able to understand better why the shopify app bridge is doing what it's doing. If we use the `console.debug` log level on the client, the logs won't show by default in developers consoles, until they adjust the logging filter! I think this'd be useful for us and for us collecting log samples from customers when things are broken.

Add some debug logging to the react-shopify-app-bridge for help debugging auth issues

---

packages/react/spec/GadgetProvider.spec.tsx
packages/react/spec/auth/useAuth.spec.ts
packages/react/spec/auth/useSession.spec.ts
packages/react/spec/auth/useSignOut.spec.ts
packages/react/spec/auth/useUser.spec.ts
packages/react/spec/components/auth/SignedIn.spec.tsx
packages/react/spec/components/auth/SignedInOrRedirect.spec.tsx
packages/react/spec/components/auth/SignedOut.spec.tsx
packages/react/spec/components/auth/SignedOutOrRedirect.spec.tsx
packages/react/spec/testWrappers.tsx
packages/react/spec/useAction.spec.tsx
packages/react/spec/useBulkAction.spec.ts
packages/react/spec/useFetch.spec.ts
packages/react/spec/useFindBy.spec.ts
packages/react/spec/useFindMany.spec.ts
packages/react/spec/useFindOne.spec.ts
packages/react/spec/useGadgetMutation.spec.ts
packages/react/spec/useGadgetQuery.spec.ts
packages/react/spec/useGet.spec.ts
packages/react/spec/useGlobalAction.spec.ts
packages/react/spec/utils.ts

Renames the test wrapper component to indicate what it is better

Quick test component rename

---

packages/react/README.md
packages/react/spec/auth/useAuth.spec.ts
packages/react/spec/auth/useSession.spec.ts
packages/react/spec/auth/useUser.spec.ts
packages/react/spec/testWrappers.tsx
packages/react/spec/utils.ts
packages/react/src/auth/useAuth.ts
packages/react/src/auth/useSession.ts
packages/react/src/auth/useUser.ts
packages/react/src/auth/utils.ts

Typed selection useSession and useUser hooks

---

packages/react/spec/useBulkAction.spec.ts
packages/react/src/useAction.ts
packages/react/src/useBulkAction.ts
packages/react/src/utils.ts

Finally figured out a way to mock these tests to test these hooks!

Fix bulk action input processing to deal with ambiguous identifiers and nested params

---

.github/workflows/test.yml
packages/test-bundles/build.ts
packages/test-bundles/package.json
pnpm-lock.yaml

So we can monitor the impact of bundle size changes over time

Add RelativeCI for bundle size monitoring

---

packages/react/spec/useFindFirst.spec.ts
packages/react/src/useFindFirst.ts
packages/react/src/useFindMany.ts
packages/react/src/useFindOne.ts

Noticed this lint failure after #274, going to add in this option

Add the pause option to hook dependencies for hygiene

---

.github/workflows/test.yml

For better insight into which bundle size changes when

Send multiple bundle sizes to relative ci

---

packages/api-client-core/package.json
packages/api-client-core/src/types.ts
pnpm-lock.yaml

Add missing transitive dependency + fix types integration tests

---

packages/react/package.json

react to 0.14.13

---

packages/api-client-core/package.json

Release a new version of the client core package

Release new version

---

packages/api-client-core/spec/operationRunners.spec.ts
packages/api-client-core/src/operationRunners.ts

Add support for find one by field operations having a maybe equivalent

---

packages/api-client-core/src/GadgetRecord.ts

While poking at the `GadgetRecord` class for some other stuff, I noticed some inefficiency in how the change tracking is implemented. `GadgetRecord` is a strange object because it is a class that has all our business logic wrapped in a proxy that allows us to do the change tracking. The objects we had back into userland are `Proxy` objects that intercept all `get` and `set` calls to do field change tracking. The actual `GadgetRecord` object sits "next" to the proxy, in that it isn't even the proxy target, but instead an object that is closed over by the proxy to provide some of the functionality. 
Previously, `GadgetRecord` stuck all its private state on a `__gadget` object on it. This adds one more object allocation to every created record object and an unnecessary layer of indirection. …

Simpler/smaller/more performant GadgetRecord

---

package.json
packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-a-single-BelongsTo-relationship_3741776720/recording.har
packages/react/spec/__recordings__/useActionFormNested_1974165259/with-polly_2612993081/can-update-multiple-HasMany-relationships-that-are-reordered_1591436327/recording.har
packages/react/spec/apis.ts
packages/react/spec/useActionFormNested.spec.tsx
packages/react/src/useActionForm.ts
pnpm-lock.yaml

Implement hasmanythrough

---

packages/react-big-commerce/package.json

react-big-commerce v0.0.1

---

packages/react/spec/auto/PolarisAutoForm.spec.tsx
packages/react/spec/auto/inputs/PolarisEncryptedStringInput.spec.tsx
packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
packages/react/src/auto/mui/inputs/MUIEncryptedStringInput.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
packages/react/src/auto/polaris/inputs/PolarisEncryptedStringInput.tsx

- **UPDATE**
- Added show/hide toggle button to encrypted string input
-  Applies to MUI and Polaris variants

Added show/hide toggle button to encrypted string input

---

packages/react/package.json

bump version, because I forgot for another bug

---

package.json
packages/react/cypress/component/auto/form/AutoForm.cy.tsx
packages/react/spec/auto/inputs/PolarisAutoPasswordInput.stories.jsx
packages/react/spec/auto/inputs/PolarisAutoRoleInput.spec.tsx
packages/react/spec/auto/inputs/PolarisPasswordInput.spec.tsx
packages/react/spec/auto/support/helper.ts
packages/react/spec/auto/support/userModel.ts
packages/react/src/auto/AutoFormContext.ts
packages/react/src/auto/mui/MUIAutoForm.tsx
packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
packages/react/src/auto/mui/inputs/MUIPasswordInput.tsx
packages/react/src/auto/polaris/PolarisAutoForm.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
packages/react/src/auto/polaris/inputs/PolarisEncryptedStringInput.tsx
packages/react/src/auto/polaris/inputs/PolarisPasswordInput.tsx
pnpm-lock.yaml

- **UPDATE**
- Added support for password fields with password replacement system when given a findBy value

Added password input component

---

.github/workflows/test.yml
packages/react/cypress.config.ts

For parity with how we test locally and what users will experience

Run real browsers for cypress in CI

---

packages/react/src/auto/mui/index.ts
packages/react/src/auto/polaris/index.ts

- **UPDATE**
- Added individual Gadget field type named exports for `AutoTextInput` so that there is always an obvious match of which component to use

Added Gadget field type specific named exports for AutoTextInput

---

packages/react/spec/auto/PolarisAutoForm.spec.tsx

This adds a test that asserts that null values are preserved through an update load and submit lifecycle, but are turned into boolean values if the user interacts with a boolean checkbox, for example, when the form is first loaded, the value of isChecked is null, but if the user selects and then unselects the checkbox, it should submit a 'false' value.

test(autoform): GGT-6652 - tests asserting null value behavior

---

.github/workflows/test.yml
packages/react/package.json
pnpm-lock.yaml

To try to fix some flakiness in cypress CI

Upgrade cypress to latest and log browser info before running tests

---

packages/react/cypress/component/auto/form/PolarisAutoDateTimePicker.cy.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoTimePicker.tsx

The Polaris date picker referenced `props.value` as the selected value, but that prop is not updated when a user picks a new date, so it was not showing a selected date when the user selected a new date.
https://github.com/gadget-inc/js-clients/assets/168455431/b61475c9-0506-4685-b1ba-2f33a4f36e56
This PR makes the date picker reference `localTime` as the selected value, since this piece of state is updated with the correct date whenever the user uses the date picker. 
https://github.com/gadget-inc/js-clients/assets/168455431/59659913-b33c-497b-bea9-777e63c888f0
💭 Should a cy test be written for this change?

GGT-6702 - Show selected date (PolarisDateTimePicker)

---

packages/react/cypress/component/auto/form/AutoForm.cy.tsx
packages/react/cypress/component/auto/form/AutoPasswordInput.cy.tsx
packages/react/cypress/component/auto/form/PolarisAutoFileInput.cy.tsx
packages/react/spec/auto/PolarisAutoForm.spec.tsx
packages/react/spec/auto/inputs/PolarisAutoBooleanIput.spec.tsx
packages/react/spec/auto/inputs/PolarisAutoJSONInput.spec.tsx
packages/react/spec/auto/inputs/PolarisAutoPasswordInput.stories.jsx
packages/react/spec/auto/inputs/PolarisAutoTextInput.spec.tsx
packages/react/src/auto/AutoForm.ts
packages/react/src/auto/mui/inputs/MUIAutoInput.tsx
packages/react/src/auto/mui/inputs/MUIAutoPasswordInput.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoPasswordInput.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoTimePicker.tsx
packages/react/src/metadata.tsx

This PR:
✅ Make time input field same size as the drop down
✅ Add cursor:pointer over numbers
❓ Add hover effect

GGT-6787 - Addressed misc design notes

---

packages/react/cypress/component/auto/form/AutoFormDynamicFormInputChanges.cy.tsx

Added test from fix forward in https://github.com/gadget-inc/js-clients/pull/522

Added test for dynamically changing findBy values on autoforms

---

packages/react/package.json
packages/react/src/useActionForm.ts

adding some debug logs for useActionForm that helped in debugging with @DevAOC

debug logging for useActionForm

---

.github/workflows/release.yml

use CYPRESS_JS_CLIENTS_TEST_API_KEY secrets in release action

---

.github/workflows/release.yml

inherit secrets

---

packages/react/cypress/component/auto/form/AutoPasswordInput.cy.tsx

- **UDPATE**
- This test is still flaking in CI when the expected variables are not included in the api request
- The first fix attempt added `cy.wait` for the api responses. It seems to have helped a bit but the flake still occurred 
- I suspect that this is a result of the changes in the input not being registered with reactHookForm before the clicking on the submit button sends them
- A 100ms wait has been added before the submit button is pressed and assigning the mock value now occurs right before the submit button is pressed

Fix test flake AutoPasswordInput.cy.tsx - Attempt 2

---

packages/react/src/useList.ts
packages/react/src/utils.ts

- **UPDATE**
- This dependency disrupts the importation of the react package. Replaced the package import with locally defined functions

Removed Lodash from react package

---

packages/react/spec/auto/PolarisAutoForm.spec.tsx
packages/react/src/auto/AutoForm.ts

- **UPDATE**
- It was previously possible to have an update/delete/custom action in an auto form without a findBy value. In this state, the `submit` button would do nothing and there would be no corresponding error
- Now, similar to the error for having a findBy on a create action, there is now an error for NOT having a findBy value on actions that require an ID input

Added error for missing findBy value for actions that require IDs

---

packages/react-bigcommerce/package.json
packages/react-shopify-app-bridge/package.json
packages/react/package.json
packages/shopify-extensions/package.json

bump deps to api-client-core 0.15.32

---

packages/react/.changeset/eight-pans-beg.md
packages/react/.changeset/fair-files-repair.md
packages/react/CHANGELOG.md
packages/react/package.json

Release @gadgetinc/react v0.17.2

---

packages/react/.changeset/poor-hairs-type.md
packages/react/spec/auto/PolarisAutoTable.stories.jsx
packages/react/spec/auto/hooks/useTable.spec.tsx
packages/react/src/auto/polaris/tableCells/PolarisAutoTableCellRenderer.tsx
packages/react/src/metadata.tsx
packages/react/src/use-table/helpers.tsx
packages/react/src/use-table/types.ts

- UPDATE
- Added HasManyThrough field support to AutoTable
- This is functionally identical to hasMany fields

Added HasManyThrough field support to AutoTable

---

packages/react-bigcommerce/package.json
packages/react-shopify-app-bridge/package.json
packages/react/.changeset/lazy-pans-push.md
packages/react/CHANGELOG.md
packages/react/package.json
packages/shopify-extensions/package.json

- Release @gadgetinc/react v0.18.1

Release @gadgetinc/react v0.18.1

---

packages/react/.changeset/big-impalas-think.md
packages/react/.changeset/brave-brooms-kneel.md
packages/react/.changeset/eleven-carrots-press.md
packages/react/.changeset/poor-jokes-bow.md
packages/react/.changeset/sixty-flowers-burn.md
packages/react/CHANGELOG.md
packages/react/package.json

Release react package v0.18.5

---

packages/react-bigcommerce/package.json
packages/react-shopify-app-bridge/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/shopify-extensions/package.json

Upgrade packages to use latest api-client-core

---

packages/react/cypress/component/auto/form/AutoFormUpsertAction.cy.tsx
packages/react/cypress/support/auto.tsx

This Input which was skipped initially is causing the main to fail

Remove Autoform  HasManyThrough fields till it is implemented

---

packages/react/cypress/component/auto/form/AutoFormJSONInput.cy.tsx
packages/react/cypress/support/auto.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoJSONInput.tsx
packages/react/src/auto/shadcn/submit/ShadcnAutoSubmit.tsx

Cypress tests for ShadcnAutoJSONinputs

Cypress tests for ShadcnAutoJSONinputs

---

packages/react/spec/auto/polaris/form/PolarisAutoRelationshipForm.stories.jsx
packages/react/src/auto/polaris/inputs/relationships/PolarisAutoBelongsToForm.tsx
packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyForm.tsx
packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx
packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasOneForm.tsx

- Added label prop to autoRelationshipForms to be consistent with other inputs 
- Update some styles for the arrangement of buttons and icons in the relationship form components

Add label prop to autoRelationshipForms and update some styles

---

packages/react-bigcommerce/package.json
packages/react-shopify-app-bridge/package.json
packages/react/package.json
packages/shopify-extensions/package.json

Update react packages to use api-client-core

---

packages/react/src/auto/shadcn/ShadcnAutoForm.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoInput.tsx

Ensure the AutoHiddenInput from shadcn is exported

---

packages/react/globals.css
packages/react/spec/auto/shadcn-defaults/components/Calendar.tsx
packages/react/tailwind.config.js

Add colors to tailwind config for shadcn

---

packages/react/package.json
scripts/check-dependency-versions.ts

New version 0.19.0 
Currently as alpha until further notice

Update @gadgetinc/react version to be 18.10 alpha

---

packages/react/spec/auto/polaris/form/PolarisAutoRelationshipForm.stories.jsx
packages/react/src/auto/polaris/inputs/relationships/PolarisAutoHasManyThroughForm.tsx

Minor style updates after consulting with design team

Minor style fixes to PolarisAutoHasManyThroughForm

---

packages/react/src/auto/interfaces/AutoRelationshipInputProps.tsx

- Added docs comments to AutoRelationshipForm props types to describe how they are used

Added docs comments to AutoRelationshipForm props types

---

packages/react/cypress/component/auto/form/AutoFormInputLabels.cy.tsx
packages/react/src/auto/hooks/useEnumInputController.tsx
packages/react/src/auto/index.tsx
packages/react/src/auto/interfaces/AutoRelationshipInputProps.tsx
packages/react/src/auto/polaris/PolarisFixedOptionsCombobox.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoEnumInput.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoIdInput.tsx
packages/react/src/auto/polaris/inputs/PolarisAutoInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoBooleanInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoDateTimePicker.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoEncryptedStringInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoEnumInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoFileInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoIdInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoJSONInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoPasswordInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoRolesInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoStringInput.tsx
packages/react/src/auto/shadcn/inputs/ShadcnAutoTextAreaInput.tsx
packages/react/src/auto/shared/AutoRichTextInputProps.tsx

ReactNode worked across the board already, but the type did not agree. Updated to make the type agree

Update AutoInput `label` prop type to `ReactNode` across the board

---

packages/react-bigcommerce/package.json
packages/react-shopify-app-bridge/package.json
packages/react/package.json
packages/shopify-extensions/package.json

Releasing `"@gadgetinc/react"` version v0.19.0
Changes
- Added new relationship form components to allow users to create, update, and delete related records through the relationship fields of an action's model.
- New components:
- `AutoHasOneForm`
- `AutoBelongsToForm`
- `AutoHasManyForm`
- `AutoHasManyThroughForm`
- See more - https://docs.gadget.dev/reference/react/auto
- Added new `recordFilter` prop to `AutoHasManyInput` and `AutoBelongsToInput` to allow the related model options in the dropdown to be filtered
- Added `findResult` to the return value of `useActionForm` for direct access to the existing record found when using the `findBy` prop
- Added `select` prop to `useAutoForm` and `AutoForm` to allow for conditional selection of fields on the existing record found when using the …

Release React pack v0.19.0

---

packages/react/src/auto/shadcn/GadgetShadcnTailwindSafelist.ts
packages/react/src/auto/shadcn/ShadcnAutoTable.tsx
packages/react/src/auto/shadcn/table/ShadcnAutoLoadingIndicator.tsx
packages/react/src/auto/shadcn/table/ShadcnAutoTableBulkActionModal.tsx
packages/react/src/auto/shadcn/table/ShadcnAutoTablePagination.tsx

- Update
- Add loading state to AutoTable
- Make alert more red and error like when there is an error in AutoTable
- Fixed z-indexing of sticky columns and rows in AutoTable. Not sure how this regressed but it is fixed now

Add loading and error state to Shadcn autoTable

---

packages/api-client-core/Changelog.md
packages/api-client-core/package.json
packages/react-bigcommerce/CHANGELOG.md
packages/react-bigcommerce/package.json
packages/react-shopify-app-bridge/CHANGELOG.md
packages/react-shopify-app-bridge/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/shopify-extensions/package.json

This PR releases the new `shopId` property introduced in https://github.com/gadget-inc/js-clients/pull/875.
If this PR will affect change user-facing behaviour, add detailed information about the change here to prompt an AI generated changelog entry.
If no changelog is required, write `no-changelog-required` in square brackets `[]`.

Bump api-client-core, react client and shopify/big-commerce package versions
